export const ENGINE_ADVERT = {
  ENGINE_MAKE: "Engine Make",
  ENGINE_MODEL: "Engine Model",
  ENGINE_TYPE: "Engine Type",
  TYPE_DESIGNATION: "Type Designation",
  MARISAIL_VESSEL_ID: "Marisail Vessel ID",
  ENGINE_CLASSIFICATION: "Engine Classification",
  CERTIFICATION: "Certification",
  CE_DESIGN_CATEGORY: "CE Design Category",
  NUMBER_DRIVES: "Number Drives",
  NUMBER_ENGINES: "Number Engines",
  RANGE_MILES: "Range (Miles)",
  CRUISING_SPEED: "Cruising Speed (Knots)",
  DRIVE_TYPE: "Drive Type",
  ENGINE_HOURS: "Engine Hours",
  IGNITION_SYSTEM: "Ignition System (Starting)",
  NOISE_LEVEL: "Noise Level (dB)",
  TRANSMISSION_TYPE: "Transmission Type",
  GEAR_SHIFT: "Gear Shift",
  GEAR_RATIO: "Gear Ratio",
  GEAR_SHIFT_TYPE: "Gear Shift Type",
  SILUMIN_FLYWHEEL_HOUSING: "Silumin Flywheel Housing",
  CAMSHAFT: "Camshaft",
  CRANKSHAFT_ALLOY: "Crankshaft Alloy",
  ENGINE_MOUNTING_TYPE: "Engine Mounting Type",
  LAST_SERVICE_DATE: "Last Service Date",
  ENGINE_MANAGEMENT_SYSTEM: "Engine Management System (EMS)",
  ENGINE_CONTROL_SYSTEM: "Engine Control System",
  TURBO_CHARGER: "Turbocharger",
  TURBO_CHARGING: "Turbocharging",
  HEAT_EXCHANGER: "Heat Exchanger",
  SEA_WATER_PUMP: "Sea Water Pump",
  AUXILIARY_POWER_TAKEOFF: "Auxiliary Power Take-Off (PTO)",
  REMOTE_CONTROL_SYSTEMS: "Remote Control Systems",
  ENGINE_MODEL_YEAR:"Engine Model Year",
  CONDITION:"Condition",
  USED_CONDITION:"Used Condition",
  SELLER:"Seller",
  OFFERED_BY:"Offered By",
  LAST_SURVEY_DATE:"Last Survey Date",
  BROKER_VALUATION:"Broker Valuation"
};
