export const varToScreen = {
    // Site Details
    siteDetails: "Site Details",
    marisailBerthId: "Marisail Berth ID",
    dataSource: "Data Source",
    // siteDetails: "Site Details",
    termsAndConditions: "Terms & Conditions",
    type: "Type",
    marinaName: "Marina / Port / Harbor Name",
    location: "Location",
    ownership: "Ownership",
    yearEstablished: "Year Established",
    operatingHours: "Operating Hours",
    contactDetails: "Contact Details",
    seasonalOperation: "Seasonal Operation",
    languageServices: "Language Services",

    // General Information
    generalInformation: "General Information",
    dockTypes: "Dock Types",
    numberOfDocks: "Number of Docks",
    boatSlipSizes: "Boat Slip Sizes",
    // location: "Location",
    numberOfBerthsAvailable: "Number of Berths Available",
    length: "Length",
    beam: "Beam",
    draft: "Draft",
    slipWidth: "Slip Width",
    slipLength: "Slip Length",
    mooringType: "Mooring Type",
    tideRange: "Tide Range",

    // Amenities & Services
    amenitiesAndServices: "Amenities & Services",
    storage: "Storage",
    electricityAvailable: "Electricity Available",
    waterSupply: "Water Supply",
    wifiAvailability: "Wi-Fi Availability",
    carParking: "Car Parking",
    conciergeServices: "Concierge Services",
    businessServices: "Business Services",
    conferenceRooms: "Conference Rooms",
    
    // Family Facilities
    familyFacilities: "Family Facilities",
    laundryFacilities: "Laundry Facilities",
    restaurantsAndCafes: "Restaurants & Cafes",
    restaurant: "Restaurant",
    bar: "Bar",
    shoppingFacilities: "Shopping Facilities",
    retailShops: "Retail Shops",
    hospitalityServices: "Hospitality Services",
    recreationalFacilities: "Recreational Facilities",
    clubhouseAccess: "Clubhouse Access",
    swimmingPool: "Swimming Pool",
    fitnessCenter: "Fitness Center",
    marinaStore: "Marina Store",
    chandlery: "Chandlery",
    restroomAndShowers: "Restroom & Showers",
    laundryServices: "Laundry Services",
    gymFacilities: "Gym Facilities",
    sanitationnFacilities: "Sanitation Facilities",
    guestAccomodationOptions: "Guest Accomodation Options",
    familyFriendlyAmenities: "Family Friendly Amenities",
    petFriendlyServices: "Pet Friendly Services",
    iceAvailability: "Ice Availability",
    picnicAndBBQAreas: "Picnic & BBQ Areas",
    childrensPlayArea: "Children's Play Area",

    // Surrounding Area
    surroundingArea: "Surrounding Area",
    localAttractions: "Local Attractions",
    restaurants: "Restaurants",
    accommodation: "Accommodation",
    shopping: "Shopping",
    transportationOptions: "Transportation Options",
    medicalFacilitesNearby: "Medical Facilities Nearby",
    localServices: "Local Services",
    communityResources: "Community Resources",

    // Additional Features
    additionalFeatures: "Additional Features",
    charterServices: "Charter Services",
    yachtBrokerageServices: "Yacht Brokerage Services",
    boatShowParticipation: "Boat Show Participation",
    loyaltyPrograms: "Loyalty Programs",
    referralPrograms: "Referral Programs",
    vipMembershipOptions: "VIP Membership Options",

    // Community & Social
    communityAndSocial: "Community & Social",
    annualEvents: "Annual Events",
    educationalPrograms: "Educational Programs",
    communityEvents: "Community Events",
    socialEvents: "Social Events",
    sportsActivities: "Sports Activities",
    culturalEvents: "Cultural Events",
    seasonalActivities: "Seasonal Activities",
    yachtClubMembership: "Yacht Club Membership",
    regattasAndCompetitions: "Regattas & Competitions",
    workshopsAndClasses: "Workshops & Classes",
    communityBulletinBoard: "Community Bulletin Board",
    networkingEvents: "Networking Events",
    memberDiscounts: "Member Discounts",

    // Services
    services: "Services",
    pumpOutStation: "Pump-Out Station",
    docksideTrolley: "Dockside Trolley",
    powerSupply: "Power Supply",
    // waterSupply: "Water Supply",
    shorePowerConnectionTypes: "Shore Power Connection Types",
    fuelTypesAvailable: "Fuel Types Available",
    fuelService: "Fuel Service",
    fuelDock: "Fuel Dock",
    electricalHookupSpecifications: "Electrical Hookup Specifications",

    // Repair & Maintenance
    repairAndMaintenance: "Repair & Maintenance",
    boatYardServices: "Boat Yard Services",
    boatCleaningServices: "Boat Cleaning Services",
    boatMaintenanceAndRepair: "Boat Maintenance & Repair",
    chandleryServices: "Chandlery Services",
    repairAndMaintenanceServices: "Repair & Maintenance Services",
    haulOutServices: "Haul-Out Services",
    boatLiftSpecifications: "Boat Lift Specifications",

    // Accessibility
    accessibility: "Accessibility",
    handicapAccessibleSlips: "Handicap Accessible Slips",
    proximityToHandicapParking: "Proximity To Handicap Parking",
    accessibleFacilities: "Accessible Facilities",
    assistanceServicesForDisabled: "Assistance Services For Disabled",
    signageAndDirections: "Signage & Directions",
    accessibleRestroomsAndShowers: "Accessible Restrooms & Showers",
    parkingFacilities: "Parking Facilities",
    accessibilityFeatures: "Accessibility Features",
    disabledAccessFacilities: "Disabled Access Facilities",
    publicTransportationLinks: "Public Transportation Links",


    // Connectivity & Transportation
    connectivityAndTransportation: "Connectivity & Transportation",
    shuttleServices: "Shuttle Services",
    transportServices: "Transport Services",
    transportLinks: "Transport Links",
    nearbyAirports: "Nearby Airports",
    publicTransportLinks: "Public Transport Links",
    taxiServices: "Taxi Services",
    bikeRentals: "Bike Rentals",
    proximityToNearbyAttractions: "Proximity To Nearby Attractions",
    carRentalServices: "Car Rental Services",
    airportTransferServices: "Airport Transfer Services",

    // Environmental Considerations
    environmentalConsiderations: "Environmental Considerations",
    environmentalCertifications: "Environmental Certifications",
    wasteDisposal: "Waste Disposal",
    wasteManagementPolicies: "Waste Management Policies",
    waterQualityMonitoring: "Water Quality Monitoring",
    wasteDisposalServices: "Waste Disposal Services",
    waterTreatmentSystems: "Water Treatment Systems",
    waterConservationMeasures: "Water Conservation Measures",
    waterHookupSpecifications: "Water Hookup Specifications",
    recyclingPrograms: "Recycling Programs",
    ecoFriendlyCleaningProducts: "Eco-Friendly Cleaning Products",
    pollutionControlMeasures: "Pollution Control Measures",
    wildlifeConservationEfforts: "Wildlife Conservation Efforts",
    greenBuildingCertifications: "Green Building Certifications",
    energySources: "Energy Sources",
    // environmentalCertifications: "Environmental Certifications",
    marineLifeProtectionMeasures: "Marine Life Protection Measures",
    greenCertifications: "Green Certifications",
    // recyclingPrograms: "Recycling Programs",
    ecoFriendlyProductsAvailability: "Eco-Friendly Products Availability",
    sewageTreatmentPlants: "Sewage Treatment Plants",

    // Security & Safety
    securityAndSafety: "Security & Safety",
    fireSafetySystems: "Fire Safety Systems",
    emergencyContactInformation: "Emergency Contact Information",
    emergencyMedicalServices: "Emergency Medical Services",
    emergencyEvacuationPlans: "Emergency Evacuation Plans",
    // emergencyContactInformation: "Emergency Contact Information",
    fireSafetyEquipment: "Fire Safety Equipment",
    firstAidKits: "First Aid Kits",
    evacuationPlan: "Evacuation Plan",
    navigationAssistance: "Navigation Assistance",
    navigationAids: "Navigation Aids",
    pilotageServices: "Pilotage Services",
    harborEntranceDepth: "Harbor Entrance Depth",
    tideInformationServices: "Tide Information Services",
    dockingDepths: "Docking Depths",
    marinaBasinDepth: "Marina Basin Depth",
    waveProtectionMeasures: "Wave Protection Measures",
    weatherMonitoringServices: "Weather Monitoring Services",
    shelterAndProtection: "Shelter & Protection",
    prevailingWinds: "Prevailing Winds",
    seaConditions: "Sea Conditions",
    breakwaterTypes: "Breakwater Types",
    weatherShelters: "Weather Shelters",
    stormPreparationServices: "Storm Preparation Services",
    floatingDockAvailability: "Floating Dock Availability",
    // safetyInspections: "Safety Inspections",
    dockConstructionMaterial: "Dock Construction Material",
    pileAnchoringSystem: "Pile Anchoring System",
    dockMaterial: "Dock Material",
    security: "Security",
    securityPatrol: "24/7 Security Patrol",
    cctvSurveillance: "CCTV Surveillance",
    accessControlSystems: "Access Control Systems",
    securityLighting: "Security Lighting",

    // Legal & Compliance
    legalAndCompliance: "Legal & Compliance",
    permitsAndLicenses: "Permits & Licenses",
    customsAndImmigration: "Customs & Immigration",
    healthAndSafetyRegulations: "Health & Safety Regulations",
    environmentalRegulationsCompliance: "Environmental Regulations Compliance",
    portStateControlInspections: "Port State Control Inspections",
    quarantineServices: "Quarantine Services",

    // Insurance & Regulations
    insuranceAndRegulations: "Insurance & Regulations",
    insuranceRequirements: "Insurance Requirements",
    liabilityInsuranceRequirements: "Liability Insurance Requirements",
    proofOfOwnershipRequired: "Proof Of Ownership Required",
    complianceWithLocalRegulations: "Compliance With Local Regulations",
    safetyInspections: "Safety Inspections",
    certificateOfSeaworthiness: "Certificate Of Seaworthiness",
    dockUseRegulations: "Dock Use Regulations",
    environmentalComplianceCertificates: "Environmental Compliance Certificates",
    
    // Financial Information
    financialInformation: "Financial Information",
    currency: "Currency",
    mooringFees: "Mooring Fees",
    serviceCharges: "Service Charges",
    membershipPrograms: "Membership Programs",
    paymentMethods: "Payment Methods",
    pricingStructure: "Pricing Structure",
    depositRequirements: "Deposit Requirements",
    cancellationPolicies: "Cancellation Policies",  
    discountsAvailable: "Discounts Available",

    // Pricing & Lease Terms
    pricingAndLeaseTerms: "Pricing & Lease Terms",
    pricePerAnnum: "Price p.a.",
    pricePerMonth: "Price PCM",
    pricePerWeek: "Price Per Week",
    availability: "Availability",
    annualLeaseRenewable: "Annual Lease Renewable",
    cancellationPolicy: "Cancellation Policy",
    latePaymentFees: "Late Payment Fees",
    // insuranceRequirements: "Insurance Requirements",

    // Payment Terms
    paymentTerms: "Payment Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred Payment Methods",
    invoiceAndReceiptProcedures: "Invoice & Receipt Procedures",
    
    // Calculate Price & Pay
    calculatePriceAndPay: "Calculate Price & Pay",
    priceLabel: "Price Label",
    priceDrop: "Price Drop",
    // currency: "Currency",
    vat: "VAT",
    totalPrice: "Total Price",

    // Country (Lying)
    country: "Country (Lying)",
    addressDetails: "Address Details",
    distance: "Distance",
    // contactDetails: "Contact Details",
    uploadPhotos: "Upload Photos",
    uploadVideos: "Upload Videos",

}

export const varToDb = {
    // Site Details
    marisailBerthId: "Marisail_Berth_ID",
    dataSource: "Data Source",
    siteDetails: "Site_Details",
    termsAndConditions: "Terms_Conditions",
    type: "Type",
    marinaName: "Name",
    location: "Location",
    ownership: "Ownership",
    yearEstablished: "Year_Established",
    operatingHours: "Operating_Hours",
    contactDetails: "Contact",
    seasonalOperation: "Seasonal_Operation",
    languageServices: "Language",

    // General Information
    dockTypes: "Dock_Types",
    numberOfDocks: "Number_Docks",
    boatSlipSizes: "Slip_Sizes",
    // location: "Location",
    numberOfBerthsAvailable: "Berths_Available",
    length: "Length",
    beam: "Beam",
    draft: "Draft",
    slipWidth: "Slip_Width",
    slipLength: "Slip_Length",
    mooringType: "Mooring_Type",
    tideRange: "Tide_Range",

    // Amenities & Services
    storage: "Storage",
    electricityAvailable: "Electricity_Available",
    waterSupply: "Water_Supply",
    wifiAvailability: "WiFi_Availability",
    carParking: "Car_Parking",
    conciergeServices: "Concierge",
    businessServices: "Business",
    conferenceRooms: "Conference_Rooms",
    
    // Family Facilities
    laundryFacilities: "Laundry_Facilities",
    restaurantsAndCafes: "Restaurants_Cafes",
    restaurant: "Restaurant",
    bar: "Bar",
    shoppingFacilities: "Shopping_Facilities",
    retailShops: "Retail_Shops",
    hospitalityServices: "Hospitality",
    recreationalFacilities: "Recreational Facilities",
    // conciergeServices: "Concierge Services",
    clubhouseAccess: "Clubhouse_Access",
    swimmingPool: "Swimming_Pool",
    fitnessCenter: "Fitness_Center",
    marinaStore: "Marina_Store",
    chandlery: "Chandlery",
    restroomAndShowers: "Restroom_Showers",
    laundryServices: "Laundry",
    gymFacilities: "Gym_Facilities",
    sanitationnFacilities: "Sanitation_Facilities",
    guestAccomodationOptions: "Guest_Accomodation_Options",
    familyFriendlyAmenities: "Family_Friendly",
    petFriendlyServices: "Pet_Friendly",
    iceAvailability: "Ice_Availability",
    picnicAndBBQAreas: "Picnic_BBQ",
    childrensPlayArea: "Childrens_Play",

    // Surrounding Area
    localAttractions: "Local_Attractions",
    restaurants: "Restaurants",
    accommodation: "Accommodation",
    shopping: "Shopping",
    transportationOptions: "Transportation",
    medicalFacilitesNearby: "Medical_Facilities",
    localServices: "Local",
    communityResources: "Community_Resources",

    // Additional Features
    charterServices: "Charter",
    yachtBrokerageServices: "Yacht_Brokerage",
    boatShowParticipation: "Boat_Show",
    loyaltyPrograms: "Loyalty_Programs",
    referralPrograms: "Referral_Programs",
    vipMembershipOptions: "VIP_Membership",

    // Community & Social
    annualEvents: "Annual_Events",
    educationalPrograms: "Educational_Programs",
    communityEvents: "Community_Events",
    socialEvents: "Social_Events",
    sportsActivities: "Sports_Activities",
    culturalEvents: "Cultural_Events",
    seasonalActivities: "Seasonal_Activities",
    yachtClubMembership: "Club_Membership",
    // socialEvents: "Social Events",
    regattasAndCompetitions: "Regattas",
    workshopsAndClasses: "Workshops_Classes",
    communityBulletinBoard: "Bulletin_Board",
    networkingEvents: "Networking_Events",
    memberDiscounts: "Member_Discounts",

    // Services
    pumpOutStation: "Pump_Station",
    docksideTrolley: "Dockside_Trolley",
    powerSupply: "Power_Supply",
    // waterSupply: "Water Supply",
    shorePowerConnectionTypes: "Power_Connection",
    fuelTypesAvailable: "Fuel_Types",
    fuelService: "Fuel_Service",
    fuelDock: "Fuel_Dock",
    electricalHookupSpecifications: "Electrical_Hookup",

    // Repair & Maintenance
    boatYardServices: "Yard",
    boatCleaningServices: "Boat_Cleaning",
    boatMaintenanceAndRepair: "Maintenance_Repair",
    chandleryServices: "Chandlery",
    repairAndMaintenanceServices: "Maintenance",
    haulOutServices: "HaulOut",
    boatLiftSpecifications: "Boat_Lift",

    // Accessibility
    handicapAccessibleSlips: "Handicap_Slips",
    proximityToHandicapParking: "Proximity_Parking",
    accessibleFacilities: "Accessible_Facilities",
    assistanceServicesForDisabled: "Assistance",
    signageAndDirections: "Signage_Directions",
    accessibleRestroomsAndShowers: "Accessible_Restrooms",
    parkingFacilities: "Parking_Facilities",
    accessibilityFeatures: "Accessibility_Features",
    disabledAccessFacilities: "Disabled_Facilities",
    publicTransportationLinks: "Transportation_Links",


    // Connectivity & Transportation
    shuttleServices: "Shuttle",
    transportServices: "Transport",
    transportLinks: "Transport_Links",
    nearbyAirports: "Nearby_Airports",
    publicTransportLinks: "Public_Transport_Links",
    taxiServices: "Taxi",
    bikeRentals: "Bike_Rentals",
    proximityToNearbyAttractions: "Nearby_Attractions",
    carRentalServices: "Car_Rental",
    airportTransferServices: "Airport_Transfer",

    // Environmental Considerations
    environmentalCertifications: "Environmental_Certifications",
    wasteDisposal: "Waste_Disposal",
    wasteManagementPolicies: "Waste_Management",
    waterQualityMonitoring: "Water_Quality",
    wasteDisposalServices: "Waste_Disposal",
    waterTreatmentSystems: "Water_Treatment",
    waterConservationMeasures: "Water_Conservation",
    waterHookupSpecifications: "Water_Hookup",
    recyclingPrograms: "Recycling_Programs",
    ecoFriendlyCleaningProducts: "EcoCleaning_Products",
    pollutionControlMeasures: "Pollution_Control",
    wildlifeConservationEfforts: "Wildlife_Conservation",
    greenBuildingCertifications: "Building_Certifications",
    energySources: "Energy_Sources",
    // environmentalCertifications: "Environmental_Certifications",
    marineLifeProtectionMeasures: "Marine_Life",
    greenCertifications: "Green_Certifications",
    // recyclingPrograms: "Recycling_Programs",
    ecoFriendlyProductsAvailability: "Eco_Friendly_Products",
    sewageTreatmentPlants: "Sewage_Treatment",

    // Security & Safety
    fireSafetySystems: "Fire_Safety",
    emergencyContactInformation: "Emergency_Contact",
    emergencyMedicalServices: "Emergency_Medical",
    emergencyEvacuationPlans: "Emergency_Evacuation",
    // emergencyContactInformation: "Emergency_Contact",
    fireSafetyEquipment: "Fire _Safety",
    firstAidKits: "First_Aid",
    evacuationPlan: "Evacuation_Plan",
    navigationAssistance: "Navigation_Assistance",
    navigationAids: "Navigation_Aids",
    pilotageServices: "Pilotage",
    harborEntranceDepth: "Harbor_Entrance_Depth",
    tideInformationServices: "Tide",
    dockingDepths: "Docking_Depths",
    marinaBasinDepth: "Marina_Basin",
    waveProtectionMeasures: "Wave_Protection",
    weatherMonitoringServices: "Weather_Monitoring",
    shelterAndProtection: "Shelter_Protection",
    prevailingWinds: "Prevailing_Winds",
    seaConditions: "Sea_Conditions",
    breakwaterTypes: "Breakwater_Types",
    weatherShelters: "Weather_Shelters",
    stormPreparationServices: "Storm_Preparation",
    floatingDockAvailability: "Floating_Dock",
    safetyInspections: "Safety_Inspections",
    dockConstructionMaterial: "Dock_Construction",
    pileAnchoringSystem: "Pile_Anchoring_System",
    dockMaterial: "Dock_Material",
    security: "Security",
    securityPatrol: "Security_Patrol",
    cctvSurveillance: "CCTV_Surveillance",
    accessControlSystems: "Access_Control",
    securityLighting: "Security_Lighting",

    // Legal & Compliance
    permitsAndLicenses: "Permits_Licenses",
    customsAndImmigration: "Customs_Immigration",
    healthAndSafetyRegulations: "Health_Safety",
    environmentalRegulationsCompliance: "Environmental_Compliance",
    portStateControlInspections: "Port_Control",
    quarantineServices: "Quarantine",

    // Insurance & Regulations
    insuranceRequirements: "Insurance",
    liabilityInsuranceRequirements: "Liability_Insurance",
    proofOfOwnershipRequired: "POO_Required",
    complianceWithLocalRegulations: "Local_Compliance",
    // safetyInspections: "Safety_Inspections",
    certificateOfSeaworthiness: "Seaworthiness_Certificate",
    dockUseRegulations: "Dock_Use",
    environmentalComplianceCertificates: "Environmental_Compliance",
    
    // Financial Information
    currency: "Currency",
    mooringFees: "Mooring_Fees",
    serviceCharges: "Service_Charges",
    membershipPrograms: "Membership_Programs",
    paymentMethods: "Payment_Methods",
    pricingStructure: "Pricing_Structure",
    depositRequirements: "Deposit",
    cancellationPolicies: "Cancellation_Policies",  
    discountsAvailable: "Discounts_Available",

    // Pricing & Lease Terms
    pricePerAnnum: "Price_PA",
    pricePerMonth: "Price_PCM",
    pricePerWeek: "Price_PW",
    availability: "Availability",
    annualLeaseRenewable: "Lease_Renewable",
    cancellationPolicy: "Cancellation_Policy",
    latePaymentFees: "Late_Fees",
    // insuranceRequirements: "Insurance",

    // Payment Terms
    paymentTerms: "Payment_Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred_Payment",
    invoiceAndReceiptProcedures: "Invoice_Receipt",
    
    // Calculate Price & Pay
    calculatePriceAndPay: "Calculate",
    priceLabel: "Price_Label",
    priceDrop: "Price_Drop",
    // currency: "Currency",
    vat: "VAT",
    // totalPrice: "Total Price",

    // Country (Lying)
    // country: "Country (Lying)",
    // addressDetails: "Address Details",
    // distance: "Distance",
    // contactDetails: "Contact Details",
    // uploadPhotos: "Upload Photos",
    // uploadVideos: "Upload Videos",
}

