export const varToScreen = {
    siteDetails: { type: "select", displayText: "Site Details", radioOptions: null },
    marisailBerthId: { type: "select", displayText: "Marisail Berth ID", radioOptions: null },
    dataSource: { type: "select", displayText: "Data Source", radioOptions: null },
    termsAndConditions: { type: "select", displayText: "Terms & Conditions", radioOptions: null },
    type: { type: "select", displayText: "Type", radioOptions: null },
    marinaName: { type: "select", displayText: "Marina / Port / Harbor Name", radioOptions: null },
    location: { type: "select", displayText: "Location", radioOptions: null },
    ownership: { type: "select", displayText: "Ownership", radioOptions: null },
    yearEstablished: { type: "select", displayText: "Year Established", radioOptions: null },
    operatingHours: { type: "select", displayText: "Operating Hours", radioOptions: null },
    contactDetails: { type: "select", displayText: "Contact Details", radioOptions: null },
    seasonalOperation: { type: "select", displayText: "Seasonal Operation", radioOptions: null },
    languageServices: { type: "select", displayText: "Language Services", radioOptions: null },

    generalInformation: { type: "select", displayText: "General Information", radioOptions: null },
    dockTypes: { type: "select", displayText: "Dock Types", radioOptions: null },
    numberOfDocks: { type: "select", displayText: "Number of Docks", radioOptions: null },
    boatSlipSizes: { type: "select", displayText: "Boat Slip Sizes", radioOptions: null },
    numberOfBerthsAvailable: { type: "select", displayText: "Number of Berths Available", radioOptions: null },
    length: { type: "range", displayText: "Length", radioOptions: [{label: "ft", value: "ft", id: 1},{label: "mtrs", value: "mtrs", id: 2}] },
    beam: { type: "range", displayText: "Beam", radioOptions: [{label: "ft", value: "ft", id: 1},{label: "mtrs", value: "mtrs", id: 2}] },
    draft: { type: "range", displayText: "Draft", radioOptions: [{label: "ft", value: "ft", id: 1},{label: "mtrs", value: "mtrs", id: 2}] },
    slipWidth: { type: "range", displayText: "Slip Width", radioOptions: [{label: "ft", value: "ft", id: 1},{label: "mtrs", value: "mtrs", id: 2}] },
    slipLength: { type: "range", displayText: "Slip Length", radioOptions: [{label: "ft", value: "ft", id: 1},{label: "mtrs", value: "mtrs", id: 2}] },
    mooringType: { type: "select", displayText: "Mooring Type", radioOptions: null },
    tideRange: { type: "select", displayText: "Tide Range", radioOptions: null },

    amenitiesAndServices: { type: "select", displayText: "Amenities & Services", radioOptions: null },
    storage: { type: "select", displayText: "Storage", radioOptions: null },
    electricityAvailable: { type: "select", displayText: "Electricity Available", radioOptions: null },
    waterSupply: { type: "select", displayText: "Water Supply", radioOptions: null },
    wifiAvailability: { type: "select", displayText: "Wi-Fi Availability", radioOptions: null },
    carParking: { type: "select", displayText: "Car Parking", radioOptions: null },
    conciergeServices: { type: "select", displayText: "Concierge Services", radioOptions: null },
    businessServices: { type: "select", displayText: "Business Services", radioOptions: null },
    conferenceRooms: { type: "select", displayText: "Conference Rooms", radioOptions: null },

    familyFacilities: { type: "select", displayText: "Family Facilities", radioOptions: null },
    laundryFacilities: { type: "select", displayText: "Laundry Facilities", radioOptions: null },
    restaurantsAndCafes: { type: "select", displayText: "Restaurants & Cafes", radioOptions: null },
    restaurant: { type: "select", displayText: "Restaurant", radioOptions: null },
    bar: { type: "select", displayText: "Bar", radioOptions: null },
    shoppingFacilities: { type: "select", displayText: "Shopping Facilities", radioOptions: null },
    retailShops: { type: "select", displayText: "Retail Shops", radioOptions: null },
    hospitalityServices: { type: "select", displayText: "Hospitality Services", radioOptions: null },
    recreationalFacilities: { type: "select", displayText: "Recreational Facilities", radioOptions: null },
    clubhouseAccess: { type: "select", displayText: "Clubhouse Access", radioOptions: null },
    swimmingPool: { type: "select", displayText: "Swimming Pool", radioOptions: null },
    fitnessCenter: { type: "select", displayText: "Fitness Center", radioOptions: null },
    marinaStore: { type: "select", displayText: "Marina Store", radioOptions: null },
    chandlery: { type: "select", displayText: "Chandlery", radioOptions: null },
    restroomAndShowers: { type: "select", displayText: "Restroom & Showers", radioOptions: null },
    laundryServices: { type: "select", displayText: "Laundry Services", radioOptions: null },
    gymFacilities: { type: "select", displayText: "Gym Facilities", radioOptions: null },
    sanitationFacilities: { type: "select", displayText: "Sanitation Facilities", radioOptions: null },
    guestAccommodationOptions: { type: "select", displayText: "Guest Accommodation Options", radioOptions: null },
    familyFriendlyAmenities: { type: "select", displayText: "Family Friendly Amenities", radioOptions: null },
    petFriendlyServices: { type: "select", displayText: "Pet Friendly Services", radioOptions: null },
    iceAvailability: { type: "select", displayText: "Ice Availability", radioOptions: null },
    picnicAndBBQAreas: { type: "select", displayText: "Picnic & BBQ Areas", radioOptions: null },
    childrensPlayArea: { type: "select", displayText: "Children's Play Area", radioOptions: null },

    sanitationnFacilities: { type: "select", displayText: "Sanitation Facilities", radioOptions: null},
    guestAccomodationOptions: { type: "select", displayText: "Guest Accomodation Options", radioOptions: null},

    surroundingArea: { type: "select", displayText: "Surrounding Area", radioOptions: null },
    localAttractions: { type: "select", displayText: "Local Attractions", radioOptions: null },
    restaurants: { type: "select", displayText: "Restaurants", radioOptions: null },
    accommodation: { type: "select", displayText: "Accommodation", radioOptions: null },
    shopping: { type: "select", displayText: "Shopping", radioOptions: null },
    transportationOptions: { type: "select", displayText: "Transportation Options", radioOptions: null },
    medicalFacilitiesNearby: { type: "select", displayText: "Medical Facilities Nearby", radioOptions: null },
    localServices: { type: "select", displayText: "Local Services", radioOptions: null },
    communityResources: { type: "select", displayText: "Community Resources", radioOptions: null },

    additionalFeatures: { type: "select", displayText: "Additional Features", radioOptions: null },
    charterServices: { type: "select", displayText: "Charter Services", radioOptions: null },
    yachtBrokerageServices: { type: "select", displayText: "Yacht Brokerage Services", radioOptions: null },
    boatShowParticipation: { type: "select", displayText: "Boat Show Participation", radioOptions: null },
    loyaltyPrograms: { type: "select", displayText: "Loyalty Programs", radioOptions: null },
    referralPrograms: { type: "select", displayText: "Referral Programs", radioOptions: null },
    vipMembershipOptions: { type: "select", displayText: "VIP Membership Options", radioOptions: null },

    communityAndSocial: { type: "select", displayText: "Community & Social", radioOptions: null },
    annualEvents: { type: "select", displayText: "Annual Events", radioOptions: null },
    educationalPrograms: { type: "select", displayText: "Educational Programs", radioOptions: null },
    communityEvents: { type: "select", displayText: "Community Events", radioOptions: null },
    socialEvents: { type: "select", displayText: "Social Events", radioOptions: null },
    sportsActivities: { type: "select", displayText: "Sports Activities", radioOptions: null },
    culturalEvents: { type: "select", displayText: "Cultural Events", radioOptions: null },
    seasonalActivities: { type: "select", displayText: "Seasonal Activities", radioOptions: null },
    yachtClubMembership: { type: "select", displayText: "Yacht Club Membership", radioOptions: null },
    regattasAndCompetitions: { type: "select", displayText: "Regattas & Competitions", radioOptions: null },
    workshopsAndClasses: { type: "select", displayText: "Workshops & Classes", radioOptions: null },
    communityBulletinBoard: { type: "select", displayText: "Community Bulletin Board", radioOptions: null },
    networkingEvents: { type: "select", displayText: "Networking Events", radioOptions: null },
    memberDiscounts: { type: "select", displayText: "Member Discounts", radioOptions: null },

    services: { type: "select", displayText: "Services", radioOptions: null },
    pumpOutStation: { type: "select", displayText: "Pump-Out Station", radioOptions: null },
    docksideTrolley: { type: "select", displayText: "Dockside Trolley", radioOptions: null },
    powerSupply: { type: "select", displayText: "Power Supply", radioOptions: null },
    shorePowerConnectionTypes: { type: "select", displayText: "Shore Power Connection Types", radioOptions: null },
    fuelTypesAvailable: { type: "select", displayText: "Fuel Types Available", radioOptions: null },
    fuelService: { type: "select", displayText: "Fuel Service", radioOptions: null },
    fuelDock: { type: "select", displayText: "Fuel Dock", radioOptions: null },
    electricalHookupSpecifications: { type: "select", displayText: "Electrical Hookup Specifications", radioOptions: null },

    repairAndMaintenance: { type: "select", displayText: "Repair & Maintenance", radioOptions: null },
    boatYardServices: { type: "select", displayText: "Boat Yard Services", radioOptions: null },
    boatCleaningServices: { type: "select", displayText: "Boat Cleaning Services", radioOptions: null },
    boatMaintenanceAndRepair: { type: "select", displayText: "Boat Maintenance & Repair", radioOptions: null },
    chandleryServices: { type: "select", displayText: "Chandlery Services", radioOptions: null },
    repairAndMaintenanceServices: { type: "select", displayText: "Repair & Maintenance Services", radioOptions: null },
    haulOutServices: { type: "select", displayText: "Haul-Out Services", radioOptions: null },
    boatLiftSpecifications: { type: "select", displayText: "Boat Lift Specifications", radioOptions: null },

    accessibility: { type: "select", displayText: "Accessibility", radioOptions: null },
    handicapAccessibleSlips: { type: "select", displayText: "Handicap Accessible Slips", radioOptions: null },
    proximityToHandicapParking: { type: "select", displayText: "Proximity To Handicap Parking", radioOptions: null },
    accessibleFacilities: { type: "select", displayText: "Accessible Facilities", radioOptions: null },
    assistanceServicesForDisabled: { type: "select", displayText: "Assistance Services For Disabled", radioOptions: null },
    signageAndDirections: { type: "select", displayText: "Signage & Directions", radioOptions: null },
    accessibleRestroomsAndShowers: { type: "select", displayText: "Accessible Restrooms & Showers", radioOptions: null },
    parkingFacilities: { type: "select", displayText: "Parking Facilities", radioOptions: null },
    accessibilityFeatures: { type: "select", displayText: "Accessibility Features", radioOptions: null },
    disabledAccessFacilities: { type: "select", displayText: "Disabled Access Facilities", radioOptions: null },
    publicTransportationLinks: { type: "select", displayText: "Public Transportation Links", radioOptions: null },

    connectivityAndTransportation: { type: "select", displayText: "Connectivity & Transportation", radioOptions: null },
    shuttleServices: { type: "select", displayText: "Shuttle Services", radioOptions: null },
    transportServices: { type: "select", displayText: "Transport Services", radioOptions: null },
    transportLinks: { type: "select", displayText: "Transport Links", radioOptions: null },
    nearbyAirports: { type: "select", displayText: "Nearby Airports", radioOptions: null },
    publicTransportLinks: { type: "select", displayText: "Public Transport Links", radioOptions: null },
    taxiServices: { type: "select", displayText: "Taxi Services", radioOptions: null },
    bikeRentals: { type: "select", displayText: "Bike Rentals", radioOptions: null },
    proximityToNearbyAttractions: { type: "select", displayText: "Proximity To Nearby Attractions", radioOptions: null },
    carRentalServices: { type: "select", displayText: "Car Rental Services", radioOptions: null },
    airportTransferServices: { type: "select", displayText: "Airport Transfer Services", radioOptions: null },

    environmentalConsiderations: { type: "select", displayText: "Environmental Considerations", radioOptions: null },
    environmentalCertifications: { type: "select", displayText: "Environmental Certifications", radioOptions: null },
    wasteDisposal: { type: "select", displayText: "Waste Disposal", radioOptions: null },
    wasteManagementPolicies: { type: "select", displayText: "Waste Management Policies", radioOptions: null },
    waterQualityMonitoring: { type: "select", displayText: "Water Quality Monitoring", radioOptions: null },
    wasteDisposalServices: { type: "select", displayText: "Waste Disposal Services", radioOptions: null },
    waterTreatmentSystems: { type: "select", displayText: "Water Treatment Systems", radioOptions: null },
    waterConservationMeasures: { type: "select", displayText: "Water Conservation Measures", radioOptions: null },
    waterHookupSpecifications: { type: "select", displayText: "Water Hookup Specifications", radioOptions: null },
    recyclingPrograms: { type: "select", displayText: "Recycling Programs", radioOptions: null },
    ecoFriendlyCleaningProducts: { type: "select", displayText: "Eco-Friendly Cleaning Products", radioOptions: null },
    pollutionControlMeasures: { type: "select", displayText: "Pollution Control Measures", radioOptions: null },
    energyEfficiencyMeasures: { type: "select", displayText: "Energy Efficiency Measures", radioOptions: null },

    wildlifeConservationEfforts: { type: "select", displayText:"Wildlife Conservation Efforts", radioOptions: null},
    greenBuildingCertifications: { type: "select", displayText:"Green Building Certifications", radioOptions: null},
    energySources: { type: "select", displayText:"Energy Sources", radioOptions: null},
    marineLifeProtectionMeasures: { type: "select", displayText:"Marine Life Protection Measures", radioOptions: null},
    greenCertifications: { type: "select", displayText:"Green Certifications", radioOptions: null},
    ecoFriendlyProductsAvailability: { type: "select", displayText:"Eco-Friendly Products Availability", radioOptions: null},
    sewageTreatmentPlants: { type: "select", displayText:"Sewage Treatment Plants", radioOptions: null},

    securityAndSafety: { type: "select", displayText: "Security & Safety", radioOptions: null },
    fireSafetySystems: { type: "select", displayText: "Fire Safety Systems", radioOptions: null },
    emergencyContactInformation: { type: "select", displayText: "Emergency Contact Information", radioOptions: null },
    emergencyMedicalServices: { type: "select", displayText: "Emergency Medical Services", radioOptions: null },
    fireSafetyEquipment: { type: "select", displayText: "Fire Safety Equipment", radioOptions: null },
    firstAidKits: { type: "select", displayText: "First Aid Kits", radioOptions: null },
    evacuationPlan: { type: "select", displayText: "Evacuation Plan", radioOptions: null },
    navigationAssistance: { type: "select", displayText: "Navigation Assistance", radioOptions: null },
    navigationAids: { type: "select", displayText: "Navigation Aids", radioOptions: null },
    pilotageServices: { type: "select", displayText: "Pilotage Services", radioOptions: null },
    harborEntranceDepth: { type: "select", displayText: "Harbor Entrance Depth", radioOptions: null },
    tideInformationServices: { type: "select", displayText: "Tide Information Services", radioOptions: null },
    dockingDepths: { type: "select", displayText: "Docking Depths", radioOptions: null },
    marinaBasinDepth: { type: "select", displayText: "Marina Basin Depth", radioOptions: null },
    waveProtectionMeasures: { type: "select", displayText: "Wave Protection Measures", radioOptions: null },
    weatherMonitoringServices: { type: "select", displayText: "Weather Monitoring Services", radioOptions: null },
    shelterAndProtection: { type: "select", displayText: "Shelter & Protection", radioOptions: null },
    prevailingWinds: { type: "select", displayText: "Prevailing Winds", radioOptions: null },
    seaConditions: { type: "select", displayText: "Sea Conditions", radioOptions: null },
    breakwaterTypes: { type: "select", displayText: "Breakwater Types", radioOptions: null },
    weatherShelters: { type: "select", displayText: "Weather Shelters", radioOptions: null },
    stormPreparationServices: { type: "select", displayText: "Storm Preparation Services", radioOptions: null },
    floatingDockAvailability: { type: "select", displayText: "Floating Dock Availability", radioOptions: null },
    dockConstructionMaterial: { type: "select", displayText: "Dock Construction Material", radioOptions: null },
    pileAnchoringSystem: { type: "select", displayText: "Pile Anchoring System", radioOptions: null },
    dockMaterial: { type: "select", displayText: "Dock Material", radioOptions: null },

    security: { type: "select", displayText: "Security", radioOptions: null },
    securityPatrol: { type: "select", displayText: "24/7 Security Patrol", radioOptions: null },
    cctvSurveillance: { type: "select", displayText: "CCTV Surveillance", radioOptions: null },
    accessControlSystems: { type: "select", displayText: "Access Control Systems", radioOptions: null },
    securityLighting: { type: "select", displayText: "Security Lighting", radioOptions: null },

    legalAndCompliance: { type: "select", displayText: "Legal & Compliance", radioOptions: null },
    permitsAndLicenses: { type: "select", displayText: "Permits & Licenses", radioOptions: null },
    customsAndImmigration: { type: "select", displayText: "Customs & Immigration", radioOptions: null },
    healthAndSafetyRegulations: { type: "select", displayText: "Health & Safety Regulations", radioOptions: null },
    environmentalRegulationsCompliance: { type: "select", displayText: "Environmental Regulations Compliance", radioOptions: null },
    portStateControlInspections: { type: "select", displayText: "Port State Control Inspections", radioOptions: null },
    quarantineServices: { type: "select", displayText: "Quarantine Services", radioOptions: null },
    emergencyEvacuationPlans: { type: "select", displayText:"Emergency Evacuation Plans", radioOptions: null},

    insuranceAndRegulations: { type: "select", displayText: "Insurance & Regulations", radioOptions: null },
    insuranceRequirements: { type: "select", displayText: "Insurance Requirements", radioOptions: null },
    liabilityInsuranceRequirements: { type: "select", displayText: "Liability Insurance Requirements", radioOptions: null },
    proofOfOwnershipRequired: { type: "select", displayText: "Proof Of Ownership Required", radioOptions: null },
    complianceWithLocalRegulations: { type: "select", displayText: "Compliance With Local Regulations", radioOptions: null },
    safetyInspections: { type: "select", displayText: "Safety Inspections", radioOptions: null },
    certificateOfSeaworthiness: { type: "select", displayText: "Certificate Of Seaworthiness", radioOptions: null },
    dockUseRegulations: { type: "select", displayText: "Dock Use Regulations", radioOptions: null },
    environmentalComplianceCertificates: { type: "select", displayText: "Environmental Compliance Certificates", radioOptions: null },

    financialInformation: { type: "select", displayText: "Financial Information", radioOptions: null },
    currency: { type: "select", displayText: "Currency", radioOptions: null },
    mooringFees: { type: "select", displayText: "Mooring Fees", radioOptions: null },
    serviceCharges: { type: "select", displayText: "Service Charges", radioOptions: null },
    membershipPrograms: { type: "select", displayText: "Membership Programs", radioOptions: null },
    paymentMethods: { type: "select", displayText: "Payment Methods", radioOptions: null },
    pricingStructure: { type: "select", displayText: "Pricing Structure", radioOptions: null },
    depositRequirements: { type: "select", displayText: "Deposit Requirements", radioOptions: null },
    cancellationPolicies: { type: "select", displayText: "Cancellation Policies", radioOptions: null },
    discountsAvailable: { type: "select", displayText: "Discounts Available", radioOptions: null },

    pricingAndLeaseTerms: { type: "select", displayText: "Pricing & Lease Terms", radioOptions: null },
    pricePerAnnum: { type: "select", displayText: "Price p.a.", radioOptions: null },
    pricePerMonth: { type: "select", displayText: "Price PCM", radioOptions: null },
    pricePerWeek: { type: "select", displayText: "Price Per Week", radioOptions: null },
    availability: { type: "select", displayText: "Availability", radioOptions: null },
    annualLeaseRenewable: { type: "select", displayText: "Annual Lease Renewable", radioOptions: null },
    cancellationPolicy: { type: "select", displayText: "Cancellation Policy", radioOptions: null },
    latePaymentFees: { type: "select", displayText: "Late Payment Fees", radioOptions: null },

    paymentTerms: { type: "select", displayText: "Payment Terms", radioOptions: null },
    preferredPaymentMethods: { type: "select", displayText: "Preferred Payment Methods", radioOptions: null },
    invoiceAndReceiptProcedures: { type: "select", displayText: "Invoice & Receipt Procedures", radioOptions: null },

    calculatePriceAndPay: { type: "select", displayText: "Calculate Price & Pay", radioOptions: null },
    priceLabel: { type: "select", displayText: "Price Label", radioOptions: null },
    priceDrop: { type: "select", displayText: "Price Drop", radioOptions: null },
    vat: { type: "select", displayText: "VAT", radioOptions: null },
    totalPrice: { type: "select", displayText: "Total Price", radioOptions: null },

    country: { type: "select", displayText: "Country (Lying)", radioOptions: null },
    addressDetails: { type: "select", displayText: "Address Details", radioOptions: null },
    distance: { type: "select", displayText: "Distance", radioOptions: null },
    uploadPhotos: { type: "select", displayText: "Upload Photos", radioOptions: null },
    uploadVideos: { type: "select", displayText: "Upload Videos", radioOptions: null },
}

export const varToDb = {
    // Site Details
    marisailBerthId: "Marisail_Berth_ID",
    dataSource: "Data Source",
    siteDetails: "Site_Details",
    termsAndConditions: "Terms_Conditions",
    type: "Type",
    marinaName: "Name",
    location: "Location",
    ownership: "Ownership",
    yearEstablished: "Year_Established",
    operatingHours: "Operating_Hours",
    contactDetails: "Contact",
    seasonalOperation: "Seasonal_Operation",
    languageServices: "Language",

    // General Information
    dockTypes: "Dock_Types",
    numberOfDocks: "Number_Docks",
    boatSlipSizes: "Slip_Sizes",
    // location: "Location",
    numberOfBerthsAvailable: "Berths_Available",
    length: "Length",
    beam: "Beam",
    draft: "Draft",
    slipWidth: "Slip_Width",
    slipLength: "Slip_Length",
    mooringType: "Mooring_Type",
    tideRange: "Tide_Range",

    // Amenities & Services
    storage: "Storage",
    electricityAvailable: "Electricity_Available",
    waterSupply: "Water_Supply",
    wifiAvailability: "WiFi_Availability",
    carParking: "Car_Parking",
    conciergeServices: "Concierge",
    businessServices: "Business",
    conferenceRooms: "Conference_Rooms",
    
    // Family Facilities
    laundryFacilities: "Laundry_Facilities",
    restaurantsAndCafes: "Restaurants_Cafes",
    restaurant: "Restaurant",
    bar: "Bar",
    shoppingFacilities: "Shopping_Facilities",
    retailShops: "Retail_Shops",
    hospitalityServices: "Hospitality",
    recreationalFacilities: "Recreational Facilities",
    // conciergeServices: "Concierge Services",
    clubhouseAccess: "Clubhouse_Access",
    swimmingPool: "Swimming_Pool",
    fitnessCenter: "Fitness_Center",
    marinaStore: "Marina_Store",
    chandlery: "Chandlery",
    restroomAndShowers: "Restroom_Showers",
    laundryServices: "Laundry",
    gymFacilities: "Gym_Facilities",
    sanitationnFacilities: "Sanitation_Facilities",
    guestAccomodationOptions: "Guest_Accomodation_Options",
    familyFriendlyAmenities: "Family_Friendly",
    petFriendlyServices: "Pet_Friendly",
    iceAvailability: "Ice_Availability",
    picnicAndBBQAreas: "Picnic_BBQ",
    childrensPlayArea: "Childrens_Play",

    // Surrounding Area
    localAttractions: "Local_Attractions",
    restaurants: "Restaurants",
    accommodation: "Accommodation",
    shopping: "Shopping",
    transportationOptions: "Transportation",
    medicalFacilitesNearby: "Medical_Facilities",
    localServices: "Local",
    communityResources: "Community_Resources",

    // Additional Features
    charterServices: "Charter",
    yachtBrokerageServices: "Yacht_Brokerage",
    boatShowParticipation: "Boat_Show",
    loyaltyPrograms: "Loyalty_Programs",
    referralPrograms: "Referral_Programs",
    vipMembershipOptions: "VIP_Membership",

    // Community & Social
    annualEvents: "Annual_Events",
    educationalPrograms: "Educational_Programs",
    communityEvents: "Community_Events",
    socialEvents: "Social_Events",
    sportsActivities: "Sports_Activities",
    culturalEvents: "Cultural_Events",
    seasonalActivities: "Seasonal_Activities",
    yachtClubMembership: "Club_Membership",
    // socialEvents: "Social Events",
    regattasAndCompetitions: "Regattas",
    workshopsAndClasses: "Workshops_Classes",
    communityBulletinBoard: "Bulletin_Board",
    networkingEvents: "Networking_Events",
    memberDiscounts: "Member_Discounts",

    // Services
    pumpOutStation: "Pump_Station",
    docksideTrolley: "Dockside_Trolley",
    powerSupply: "Power_Supply",
    // waterSupply: "Water Supply",
    shorePowerConnectionTypes: "Power_Connection",
    fuelTypesAvailable: "Fuel_Types",
    fuelService: "Fuel_Service",
    fuelDock: "Fuel_Dock",
    electricalHookupSpecifications: "Electrical_Hookup",

    // Repair & Maintenance
    boatYardServices: "Yard",
    boatCleaningServices: "Boat_Cleaning",
    boatMaintenanceAndRepair: "Maintenance_Repair",
    chandleryServices: "Chandlery",
    repairAndMaintenanceServices: "Maintenance",
    haulOutServices: "HaulOut",
    boatLiftSpecifications: "Boat_Lift",

    // Accessibility
    handicapAccessibleSlips: "Handicap_Slips",
    proximityToHandicapParking: "Proximity_Parking",
    accessibleFacilities: "Accessible_Facilities",
    assistanceServicesForDisabled: "Assistance",
    signageAndDirections: "Signage_Directions",
    accessibleRestroomsAndShowers: "Accessible_Restrooms",
    parkingFacilities: "Parking_Facilities",
    accessibilityFeatures: "Accessibility_Features",
    disabledAccessFacilities: "Disabled_Facilities",
    publicTransportationLinks: "Transportation_Links",


    // Connectivity & Transportation
    shuttleServices: "Shuttle",
    transportServices: "Transport",
    transportLinks: "Transport_Links",
    nearbyAirports: "Nearby_Airports",
    publicTransportLinks: "Public_Transport_Links",
    taxiServices: "Taxi",
    bikeRentals: "Bike_Rentals",
    proximityToNearbyAttractions: "Nearby_Attractions",
    carRentalServices: "Car_Rental",
    airportTransferServices: "Airport_Transfer",

    // Environmental Considerations
    environmentalCertifications: "Environmental_Certifications",
    wasteDisposal: "Waste_Disposal",
    wasteManagementPolicies: "Waste_Management",
    waterQualityMonitoring: "Water_Quality",
    wasteDisposalServices: "Waste_Disposal",
    waterTreatmentSystems: "Water_Treatment",
    waterConservationMeasures: "Water_Conservation",
    waterHookupSpecifications: "Water_Hookup",
    recyclingPrograms: "Recycling_Programs",
    ecoFriendlyCleaningProducts: "EcoCleaning_Products",
    pollutionControlMeasures: "Pollution_Control",
    wildlifeConservationEfforts: "Wildlife_Conservation",
    greenBuildingCertifications: "Building_Certifications",
    energySources: "Energy_Sources",
    // environmentalCertifications: "Environmental_Certifications",
    marineLifeProtectionMeasures: "Marine_Life",
    greenCertifications: "Green_Certifications",
    // recyclingPrograms: "Recycling_Programs",
    ecoFriendlyProductsAvailability: "Eco_Friendly_Products",
    sewageTreatmentPlants: "Sewage_Treatment",

    // Security & Safety
    fireSafetySystems: "Fire_Safety",
    emergencyContactInformation: "Emergency_Contact",
    emergencyMedicalServices: "Emergency_Medical",
    emergencyEvacuationPlans: "Emergency_Evacuation",
    // emergencyContactInformation: "Emergency_Contact",
    fireSafetyEquipment: "Fire _Safety",
    firstAidKits: "First_Aid",
    evacuationPlan: "Evacuation_Plan",
    navigationAssistance: "Navigation_Assistance",
    navigationAids: "Navigation_Aids",
    pilotageServices: "Pilotage",
    harborEntranceDepth: "Harbor_Entrance_Depth",
    tideInformationServices: "Tide",
    dockingDepths: "Docking_Depths",
    marinaBasinDepth: "Marina_Basin",
    waveProtectionMeasures: "Wave_Protection",
    weatherMonitoringServices: "Weather_Monitoring",
    shelterAndProtection: "Shelter_Protection",
    prevailingWinds: "Prevailing_Winds",
    seaConditions: "Sea_Conditions",
    breakwaterTypes: "Breakwater_Types",
    weatherShelters: "Weather_Shelters",
    stormPreparationServices: "Storm_Preparation",
    floatingDockAvailability: "Floating_Dock",
    safetyInspections: "Safety_Inspections",
    dockConstructionMaterial: "Dock_Construction",
    pileAnchoringSystem: "Pile_Anchoring_System",
    dockMaterial: "Dock_Material",
    security: "Security",
    securityPatrol: "Security_Patrol",
    cctvSurveillance: "CCTV_Surveillance",
    accessControlSystems: "Access_Control",
    securityLighting: "Security_Lighting",

    // Legal & Compliance
    permitsAndLicenses: "Permits_Licenses",
    customsAndImmigration: "Customs_Immigration",
    healthAndSafetyRegulations: "Health_Safety",
    environmentalRegulationsCompliance: "Environmental_Compliance",
    portStateControlInspections: "Port_Control",
    quarantineServices: "Quarantine",

    // Insurance & Regulations
    insuranceRequirements: "Insurance",
    liabilityInsuranceRequirements: "Liability_Insurance",
    proofOfOwnershipRequired: "POO_Required",
    complianceWithLocalRegulations: "Local_Compliance",
    // safetyInspections: "Safety_Inspections",
    certificateOfSeaworthiness: "Seaworthiness_Certificate",
    dockUseRegulations: "Dock_Use",
    environmentalComplianceCertificates: "Environmental_Compliance",
    
    // Financial Information
    currency: "Currency",
    mooringFees: "Mooring_Fees",
    serviceCharges: "Service_Charges",
    membershipPrograms: "Membership_Programs",
    paymentMethods: "Payment_Methods",
    pricingStructure: "Pricing_Structure",
    depositRequirements: "Deposit",
    cancellationPolicies: "Cancellation_Policies",  
    discountsAvailable: "Discounts_Available",

    // Pricing & Lease Terms
    pricePerAnnum: "Price_PA",
    pricePerMonth: "Price_PCM",
    pricePerWeek: "Price_PW",
    availability: "Availability",
    annualLeaseRenewable: "Lease_Renewable",
    cancellationPolicy: "Cancellation_Policy",
    latePaymentFees: "Late_Fees",
    // insuranceRequirements: "Insurance",

    // Payment Terms
    paymentTerms: "Payment_Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred_Payment",
    invoiceAndReceiptProcedures: "Invoice_Receipt",
    
    // Calculate Price & Pay
    calculatePriceAndPay: "Calculate",
    priceLabel: "Price_Label",
    priceDrop: "Price_Drop",
    // currency: "Currency",
    vat: "VAT",
    // totalPrice: "Total Price",

    // Country (Lying)
    // country: "Country (Lying)",
    // addressDetails: "Address Details",
    // distance: "Distance",
    // contactDetails: "Contact Details",
    // uploadPhotos: "Upload Photos",
    // uploadVideos: "Upload Videos",
}

export const defaultUnit = {
    length: "Meters",
    beam: "Meters",
    draft: "Meters",
    slipWidth: "Meters",
    slipLength: "Meters",
}

