export const keyToExpectedValueMap =
{
    marinaPortHarborName: "Marina/Port/Harbor Name",
    wifiAvailability: "Wi-Fi Availability",
    familyFriendlyAmenities: "Family-Friendly Amenities",
    petFriendlyServices: "Pet-Friendly Services",
    pumpOutStation: "Pump-Out Station",
    haulOutServices: "Haul-Out Services",
    ecoFriendlyCleaningProducts: "Eco-Friendly Cleaning Products",
    ecoFriendlyProductsAvailability: "Eco-Friendly Products Availability",
    security24_7: "24/7 Security Patrol",
    vat: "VAT",
    pricePA: "Price p.a.",
    picnicAndBBQAreas: "Picnic & BBQ Areas",
    childrensPlayArea: "Children's Play Area",
    price_pcm: "Price PCM"
}

export const typeDef = {
    siteDetails: {
        marisailBerthId: { value: "", type: "radio", mandatory: true },
        siteDetails: { value: "", type: "radio", mandatory: true },
        termsAndConditions: { value: "", type: "radio", mandatory: true },
        type: { value: "", type: "radio", mandatory: true },
        marinaPortHarborName: { value: "", type: "radio", mandatory: true },
        location: { value: "", type: "radio", mandatory: true },
        ownership: { value: "", type: "radio", mandatory: true },
        yearEstablished: { value: "", type: "radio", mandatory: true },
        operatingHours: { value: "", type: "radio", mandatory: true },
        contactDetails: { value: "", type: "radio", mandatory: true },
        seasonalOperation: { value: "", type: "radio", mandatory: true },
        languageServices: { value: "", type: "radio", mandatory: true },
    },
    generalInformation: {
        dockTypes: { value: "", type: "radio", mandatory: true },
        numberOfDocks: { value: "", type: "radio", mandatory: true },
        boatSlipSizes: { value: "", type: "radio", mandatory: true },
        numberBerthsAvailable: { value: "", type: "radio", mandatory: true },
        length: { value: "", type: "radio", mandatory: true },
        beam: { value: "", type: "radio", mandatory: true },
        draft: { value: "", type: "radio", mandatory: true },
        slipWidth: { value: "", type: "radio", mandatory: true },
        slipDepth: { value: "", type: "radio", mandatory: true },
        slipLength: { value: "", type: "radio", mandatory: true },
        mooringType: { value: "", type: "radio", mandatory: true },
        tideRange: { value: "", type: "radio", mandatory: true },
    },
    amenitiesAndServices: {
        storage: { value: "", type: "radio", mandatory: false },
        electricityAvailable: { value: "", type: "radio", mandatory: true },
        waterSupply: { value: "", type: "radio", mandatory: true },
        wifiAvailability: { value: "", type: "radio", mandatory: true },
        carParking: { value: "", type: "radio", mandatory: true },
        conciergeServices: { value: "", type: "radio", mandatory: false },
        businessServices: { value: "", type: "radio", mandatory: false },
        conferenceRooms: { value: "", type: "radio", mandatory: false },
    },
    familyFacilities: {
        laundryFacilities: { value: "", type: "radio", mandatory: true },
        restaurantsAndCafes: { value: "", type: "radio", mandatory: true },
        restaurant: { value: "", type: "radio", mandatory: true },
        bar: { value: "", type: "radio", mandatory: true },
        shoppingFacilities: { value: "", type: "radio", mandatory: true },
        retailShops: { value: "", type: "radio", mandatory: true },
        hospitalityServices: { value: "", type: "radio", mandatory: true },
        recreationalFacilities: { value: "", type: "radio", mandatory: false },
        conciergeServices: { value: "", type: "radio", mandatory: false },
        clubhouseAccess: { value: "", type: "radio", mandatory: true },
        swimmingPool: { value: "", type: "radio", mandatory: true },
        fitnessCenter: { value: "", type: "radio", mandatory: true },
        marinaStore: { value: "", type: "radio", mandatory: true },
        chandlery: { value: "", type: "radio", mandatory: true },
        restroomsAndShowers: { value: "", type: "radio", mandatory: true },
        laundryServices: { value: "", type: "radio", mandatory: true },
        gymFacilities: { value: "", type: "radio", mandatory: true },
        sanitationFacilities: { value: "", type: "radio", mandatory: false },
        guestAccommodationOptions: { value: "", type: "radio", mandatory: false },
        familyFriendlyAmenities: { value: "", type: "radio", mandatory: true },
        petFriendlyServices: { value: "", type: "radio", mandatory: true },
        iceAvailability: { value: "", type: "radio", mandatory: false },
        picnicAndBBQAreas: { value: "", type: "radio", mandatory: false },
        childrensPlayArea: { value: "", type: "radio", mandatory: false },
    },
    surroundingArea: {
        localAttractions: { value: "", type: "radio", mandatory: false },
        restaurants: { value: "", type: "radio", mandatory: false },
        accommodation: { value: "", type: "radio", mandatory: false },
        shopping: { value: "", type: "radio", mandatory: false },
        transportationOptions: { value: "", type: "radio", mandatory: false },
        medicalFacilitiesNearby: { value: "", type: "radio", mandatory: false },
        localServices: { value: "", type: "radio", mandatory: false },
        communityResources: { value: "", type: "radio", mandatory: false },
    },
    additionalFeatures: {
        charterServices: { value: "", type: "radio", mandatory: false },
        yachtBrokerageServices: { value: "", type: "radio", mandatory: false },
        boatShowParticipation: { value: "", type: "radio", mandatory: false },
        loyaltyPrograms: { value: "", type: "radio", mandatory: false },
        referralPrograms: { value: "", type: "radio", mandatory: false },
        vip_MembershipOptions: { value: "", type: "radio", mandatory: false },
    },
    communityAndSocial: {
        annualEvents: { value: "", type: "radio", mandatory: false },
        educationalPrograms: { value: "", type: "radio", mandatory: false },
        communityEvents: { value: "", type: "radio", mandatory: false },
        socialEvents: { value: "", type: "radio", mandatory: false },
        sportsActivities: { value: "", type: "radio", mandatory: false },
        culturalEvents: { value: "", type: "radio", mandatory: false },
        seasonalActivities: { value: "", type: "radio", mandatory: false },
        yachtClubMembership: { value: "", type: "radio", mandatory: true },
        regattasAndCompetitions: { value: "", type: "radio", mandatory: false },
        workshopsAndClasses: { value: "", type: "radio", mandatory: false },
        communityBulletinBoard: { value: "", type: "radio", mandatory: false },
        networkingEvents: { value: "", type: "radio", mandatory: false },
        memberDiscounts: { value: "", type: "radio", mandatory: false },
    },
    services: {
        pumpOutStation: { value: "", type: "radio", mandatory: false },
        docksideTrolley: { value: "", type: "radio", mandatory: true },
        powerSupply: { value: "", type: "radio", mandatory: false },
        waterSupply: { value: "", type: "radio", mandatory: false },
        shorePowerConnectionTypes: { value: "", type: "radio", mandatory: false },
        fuelTypesAvailable: { value: "", type: "radio", mandatory: true },
        fuelService: { value: "", type: "radio", mandatory: false },
        fuelDock: { value: "", type: "radio", mandatory: true },
        electricalHookupSpecifications: {
            value: "",
            type: "radio",
            mandatory: true,
        },
    },
    repairAndMaintenance: {
        boatYardServices: { value: "", type: "radio", mandatory: false },
        boatCleaningServices: { value: "", type: "radio", mandatory: false },
        boatMaintenanceRepair: { value: "", type: "radio", mandatory: false },
        chandleryServices: { value: "", type: "radio", mandatory: false },
        repairAndMaintenanceServices: { value: "", type: "radio", mandatory: false },
        haulOutServices: { value: "", type: "radio", mandatory: false },
        boatLiftSpecifications: { value: "", type: "radio", mandatory: true },
    },
    accessibility: {
        handicapAccessibleSlips: { value: "", type: "radio", mandatory: true },
        proximityHandicapParking: { value: "", type: "radio", mandatory: true },
        accessibleFacilities: { value: "", type: "radio", mandatory: true },
        assistanceServicesDisabled: { value: "", type: "radio", mandatory: true },
        signageAndDirections: { value: "", type: "radio", mandatory: true },
        accessibleRestroomsShowers: { value: "", type: "radio", mandatory: true },
        parkingFacilities: { value: "", type: "radio", mandatory: false },
        accessibilityFeatures: { value: "", type: "radio", mandatory: false },
        disabledAccessFacilities: { value: "", type: "radio", mandatory: false },
        publicTransportLinks: { value: "", type: "radio", mandatory: false },
    },
    connectivityAndTransportation: {
        shuttleServices: { value: "", type: "radio", mandatory: false },
        transportServices: { value: "", type: "radio", mandatory: false },
        transportLinks: { value: "", type: "radio", mandatory: false },
        nearbyAirports: { value: "", type: "radio", mandatory: false },
        taxiServices: { value: "", type: "radio", mandatory: true },
        bikeRentals: { value: "", type: "radio", mandatory: false },
        proximityToAttractions: { value: "", type: "radio", mandatory: false },
        carRentalServices: { value: "", type: "radio", mandatory: false },
        airportTransferServices: { value: "", type: "radio", mandatory: false },
    },
    environmentalConsiderations: {
        environmentalCertifications: { value: "", type: "radio", mandatory: false },
        wasteDisposal: { value: "", type: "radio", mandatory: true },
        wasteManagementPolicies: { value: "", type: "radio", mandatory: false },
        waterQualityMonitoring: { value: "", type: "radio", mandatory: false },
        wasteDisposalServices: { value: "", type: "radio", mandatory: false },
        waterTreatmentSystems: { value: "", type: "radio", mandatory: false },
        waterConservationMeasures: { value: "", type: "radio", mandatory: false },
        waterHookupSpecifications: { value: "", type: "radio", mandatory: true },
        recyclingPrograms: { value: "", type: "radio", mandatory: false },
        ecoFriendlyCleaningProducts: { value: "", type: "radio", mandatory: false },
        pollutionControlMeasures: { value: "", type: "radio", mandatory: false },
        wildlifeConservationEfforts: { value: "", type: "radio", mandatory: false },
        greenBuildingCertifications: { value: "", type: "radio", mandatory: false },
        energySources: { value: "", type: "radio", mandatory: false },
        marineLifeProtectionMeasures: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        greenCertifications: { value: "", type: "radio", mandatory: false },
        ecoFriendlyProductsAvailability: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        sewageTreatmentPlants: { value: "", type: "radio", mandatory: false },
    },
    securityAndSafety: {
        fireSafetySystems: { value: "", type: "radio", mandatory: false },
        emergencyContactInformation: { value: "", type: "radio", mandatory: false }, // Contact Details Page
        emergencyMedicalServices: { value: "", type: "radio", mandatory: false },
        emergencyEvacuationPlans: { value: "", type: "radio", mandatory: false },
        fireSafetyEquipment: { value: "", type: "radio", mandatory: true },
        firstAidKits: { value: "", type: "radio", mandatory: true },
        evacuationPlan: { value: "", type: "radio", mandatory: false },
        navigationAssistance: { value: "", type: "radio", mandatory: false },
        navigationAids: { value: "", type: "radio", mandatory: false },
        harborEntranceDepth: { value: "", type: "radio", mandatory: false },
        dockingDepths: { value: "", type: "radio", mandatory: false },
        marinaBasinDepth: { value: "", type: "radio", mandatory: false },
        waveProtectionMeasures: { value: "", type: "radio", mandatory: false },
        weatherMonitoringServices: { value: "", type: "radio", mandatory: false },
        shelterAndProtection: { value: "", type: "radio", mandatory: false },
        prevailingWinds: { value: "", type: "radio", mandatory: false },
        seaConditions: { value: "", type: "radio", mandatory: false },
        breakwaterTypes: { value: "", type: "radio", mandatory: false },
        weatherShelters: { value: "", type: "radio", mandatory: false },
        stormPreparationServices: { value: "", type: "radio", mandatory: false },
        floatingDockAvailability: { value: "", type: "radio", mandatory: false },
        dockConstructionMaterial: { value: "", type: "radio", mandatory: false },
        pileAnchoringSystem: { value: "", type: "radio", mandatory: false },
        security: { value: "", type: "radio", mandatory: false },
        security24_7: { value: "", type: "radio", mandatory: true },
        cctv_Surveillance: { value: "", type: "radio", mandatory: true },
        accessControlSystems: { value: "", type: "radio", mandatory: false },
        securityLighting: { value: "", type: "radio", mandatory: false },
    },
    legalAndCompliance: {
        permitsAndLicenses: { value: "", type: "radio", mandatory: false },
        customsAndImmigration: { value: "", type: "radio", mandatory: false },
        healthAndSafetyRegulations: { value: "", type: "radio", mandatory: false },
        environmentalRegulationsCompliance: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        portStateControlInspections: { value: "", type: "radio", mandatory: false },
        quarantineServices: { value: "", type: "radio", mandatory: false },
    },
    insuranceAndRegulations: {
        insuranceRequirements: { value: "", type: "radio", mandatory: false },
        liabilityInsuranceRequirements: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        proofOfOwnershipRequired: { value: "", type: "radio", mandatory: false },
        complianceWithLocalRegulations: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        safetyInspections: { value: "", type: "radio", mandatory: false },
        certificateOfSeaworthiness: { value: "", type: "radio", mandatory: false },
        dockUseRegulations: { value: "", type: "radio", mandatory: false },
        environmentalComplianceCertificates: {
            value: "",
            type: "radio",
            mandatory: false,
        },
    },
    financialInformation: {
        currency: { value: "", type: "radio", mandatory: true },
        mooringFees: { value: "", type: "radio", mandatory: false },
        serviceCharges: { value: "", type: "radio", mandatory: false },
        membershipPrograms: { value: "", type: "radio", mandatory: false },
        paymentMethods: { value: "", type: "radio", mandatory: false },
        pricingStructure: { value: "", type: "radio", mandatory: false },
        depositRequirements: { value: "", type: "radio", mandatory: false },
        cancellationPolicies: { value: "", type: "radio", mandatory: false },
        discountsAvailable: { value: "", type: "radio", mandatory: false },
    },
    pricingAndLeaseTerms: {
        pricePA: { value: "", type: "radio", mandatory: true },
        price_pcm: { value: "", type: "radio", mandatory: true },
        pricePerWeek: { value: "", type: "radio", mandatory: true },
        availability: { value: "", type: "radio", mandatory: true },
        annualLeaseRenewable: { value: "", type: "radio", mandatory: true },
        cancellationPolicy: { value: "", type: "radio", mandatory: true },
        latePaymentFees: { value: "", type: "radio", mandatory: true },
        insuranceRequirements: { value: "", type: "radio", mandatory: true },
    },
    paymentTerms: {
        paymentTerms: { value: "", type: "radio", mandatory: true },
        currency: { value: "", type: "radio", mandatory: true },
        preferredPaymentMethods: { value: "", type: "radio", mandatory: true },
        invoiceAndReceiptProcedures: { value: "", type: "radio", mandatory: true },
        calculatePriceAndPay: { value: "", type: "radio", mandatory: false },
        priceLabel: { value: "", type: "radio", mandatory: false },
        priceDrop: { value: "", type: "radio", mandatory: false },
        vat: { value: "", type: "radio", mandatory: false },
        totalPrice: { value: "", type: "radio", mandatory: false },
    },
};