export const keyToExpectedValueMap = {
    marinaPortHarborName: "Marina/Port/Harbor Name",
    wifiAvailability: "Wi-Fi Availability",
    familyFriendlyAmenities: "Family-Friendly Amenities",
    petFriendlyServices: "Pet-Friendly Services",
    pumpOutStation: "Pump-Out Station",
    haulOutServices: "Haul-Out Services",
    ecoFriendlyCleaningProducts: "Eco-Friendly Cleaning Products",
    ecoFriendlyProductsAvailability: "Eco-Friendly Products Availability",
    security24_7: "24/7 Security Patrol",
    vat: "VAT",
    pricePA: "Price p.a.",
    picnicAndBBQAreas: "Picnic & BBQ Areas",
    childrensPlayArea: "Children's Play Area",
    price_pcm: "Price PCM",
};

export const radioOptions = [
    { label: "ft", value: "ft", id:1 },
    { label: "mtrs", value: "mtrs", id:2 },
];

export const typeDef = {
    siteDetails: {
        marisailBerthId: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        siteDetails: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        termsAndConditions: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        type: { value: "", type: "radio", mandatory: true, radioOptions: null },
        marinaPortHarborName: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        location: { value: "", type: "radio", mandatory: true, radioOptions: null },
        ownership: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        yearEstablished: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        operatingHours: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        contactDetails: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        seasonalOperation: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        languageServices: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
    },
    generalInformation: {
        dockTypes: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        numberOfDocks: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        boatSlipSizes: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        numberBerthsAvailable: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        length: {
            value: "",
            type: "dual",
            mandatory: true,
            radioOptions: [
                { label: "ft", value: "ft", id: 1 },
                { label: "mtrs", value: "mtrs", id: 2 },
            ],
        },
        beam: {
            value: "",
            type: "dual",
            mandatory: true,
            radioOptions: [
                { label: "ft", value: "ft", id: 1 },
                { label: "mtrs", value: "mtrs", id: 2 },
            ],
        },
        draft: {
            value: "",
            type: "dual",
            mandatory: true,
            radioOptions: [
                { label: "ft", value: "ft", id: 1 },
                { label: "mtrs", value: "mtrs", id: 2 },
            ],
        },
        slipWidth: {
            value: "",
            type: "dual",
            mandatory: true,
            radioOptions: [
                { label: "ft", value: "ft", id: 1 },
                { label: "mtrs", value: "mtrs", id: 2 },
            ],
        },
        slipDepth: {
            value: "",
            type: "dual",
            mandatory: true,
            radioOptions: [
                { label: "ft", value: "ft", id: 1 },
                { label: "mtrs", value: "mtrs", id: 2 },
            ],
        },
        slipLength: {
            value: "",
            type: "dual",
            mandatory: true,
            radioOptions: [
                { label: "ft", value: "ft", id: 1 },
                { label: "mtrs", value: "mtrs", id: 2 },
            ],
        },
        mooringType: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        tideRange: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
    },
    amenitiesAndServices: {
        storage: { value: "", type: "radio", mandatory: false, radioOptions: null },
        electricityAvailable: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        waterSupply: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        wifiAvailability: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        carParking: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        conciergeServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        businessServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        conferenceRooms: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    familyFacilities: {
        laundryFacilities: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        restaurantsAndCafes: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        restaurant: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        bar: { value: "", type: "radio", mandatory: true, radioOptions: null },
        shoppingFacilities: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        retailShops: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        hospitalityServices: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        recreationalFacilities: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        conciergeServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        clubhouseAccess: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        swimmingPool: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        fitnessCenter: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        marinaStore: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        chandlery: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        restroomsAndShowers: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        laundryServices: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        gymFacilities: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        sanitationFacilities: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        guestAccommodationOptions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        familyFriendlyAmenities: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        petFriendlyServices: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        iceAvailability: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        picnicAndBBQAreas: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        childrensPlayArea: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    surroundingArea: {
        localAttractions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        restaurants: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        accommodation: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        shopping: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        transportationOptions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        medicalFacilitiesNearby: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        localServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        communityResources: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    additionalFeatures: {
        charterServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        yachtBrokerageServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        boatShowParticipation: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        loyaltyPrograms: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        referralPrograms: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        vip_MembershipOptions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    communityAndSocial: {
        annualEvents: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        educationalPrograms: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        communityEvents: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        socialEvents: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        sportsActivities: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        culturalEvents: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        seasonalActivities: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        yachtClubMembership: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        regattasAndCompetitions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },

    services: {
        pumpOutStation: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        docksideTrolley: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        powerSupply: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        waterSupply: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        shorePowerConnectionTypes: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        fuelTypesAvailable: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        fuelService: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        fuelDock: { value: "", type: "radio", mandatory: true, radioOptions: null },
        electricalHookupSpecifications: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
    },
    repairAndMaintenance: {
        boatYardServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        boatCleaningServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        boatMaintenanceRepair: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        chandleryServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        repairAndMaintenanceServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        haulOutServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        boatLiftSpecifications: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
    },
    accessibility: {
        handicapAccessibleSlips: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        proximityHandicapParking: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        accessibleFacilities: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        assistanceServicesDisabled: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        signageAndDirections: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        accessibleRestroomsShowers: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        parkingFacilities: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        accessibilityFeatures: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        disabledAccessFacilities: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        publicTransportLinks: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    connectivityAndTransportation: {
        shuttleServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        transportServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        transportLinks: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        nearbyAirports: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        taxiServices: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        bikeRentals: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        proximityToAttractions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        carRentalServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        airportTransferServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    environmentalConsiderations: {
        environmentalCertifications: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        wasteDisposal: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        wasteManagementPolicies: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        waterQualityMonitoring: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        wasteDisposalServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        waterTreatmentSystems: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        waterConservationMeasures: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        waterHookupSpecifications: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        recyclingPrograms: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        ecoFriendlyCleaningProducts: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        pollutionControlMeasures: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        wildlifeConservationEfforts: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        greenBuildingCertifications: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        energySources: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        marineLifeProtectionMeasures: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        greenCertifications: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        ecoFriendlyProductsAvailability: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        sewageTreatmentPlants: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    securityAndSafety: {
        fireSafetySystems: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        emergencyContactInformation: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        emergencyMedicalServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        emergencyEvacuationPlans: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        fireSafetyEquipment: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        firstAidKits: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        evacuationPlan: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        navigationAssistance: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        navigationAids: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        harborEntranceDepth: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        dockingDepths: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        marinaBasinDepth: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        waveProtectionMeasures: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        weatherMonitoringServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        shelterAndProtection: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        prevailingWinds: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        seaConditions: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        breakwaterTypes: {
            value: "",
            type: "dual",
            mandatory: false,
            radioOptions: [
                { label: "hp", value: "hp", id: 1 },
                { label: "kW", value: "kW", id: 2 },
            ],
        },
        weatherShelters: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        stormPreparationServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        floatingDockAvailability: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        dockConstructionMaterial: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        pileAnchoringSystem: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        security: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        security24_7: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        cctv_Surveillance: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        accessControlSystems: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        securityLighting: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    legalAndCompliance: {
        permitsAndLicenses: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        customsAndImmigration: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        healthAndSafetyRegulations: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        environmentalRegulationsCompliance: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        portStateControlInspections: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        quarantineServices: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    insuranceAndRegulations: {
        insuranceRequirements: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        liabilityInsuranceRequirements: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        proofOfOwnershipRequired: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        complianceWithLocalRegulations: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        safetyInspections: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        certificateOfSeaworthiness: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        dockUseRegulations: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        environmentalComplianceCertificates: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    financialInformation: {
        currency: { value: "", type: "radio", mandatory: true, radioOptions: null },
        mooringFees: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        serviceCharges: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        membershipPrograms: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        paymentMethods: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        pricingStructure: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        depositRequirements: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        cancellationPolicies: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        discountsAvailable: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
    pricingAndLeaseTerms: {
        pricePA: { value: "", type: "radio", mandatory: true, radioOptions: null },
        price_pcm: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        pricePerWeek: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        availability: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        annualLeaseRenewable: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        cancellationPolicy: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        latePaymentFees: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        insuranceRequirements: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
    },
    paymentTerms: {
        paymentTerms: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        currency: { value: "", type: "radio", mandatory: true, radioOptions: null },
        preferredPaymentMethods: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        invoiceAndReceiptProcedures: {
            value: "",
            type: "radio",
            mandatory: true,
            radioOptions: null,
        },
        calculatePriceAndPay: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        priceLabel: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        priceDrop: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
        vat: { value: "", type: "radio", mandatory: false, radioOptions: null },
        totalPrice: {
            value: "",
            type: "radio",
            mandatory: false,
            radioOptions: null,
        },
    },
};
