export const typeDef = {
  identification: {
    marisailTrailerId: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    manufacturer: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    make: { value: "", type: "radio", mandatory: true, radioOptions: null },
    model: { value: "", type: "radio", mandatory: true, radioOptions: null },
    year: { value: "", type: "radio", mandatory: true, radioOptions: null },
    askingPrice: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  basics: {
    type: { value: "", type: "radio", mandatory: true, radioOptions: null },
    gvwr: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "lbs", value: "lbs", id: 1 },
        { label: "Kgs", value: "Kgs", id: 2 },
      ],
    },
    loadCapacity: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "lbs", value: "lbs", id: 1 },
        { label: "Kgs", value: "Kgs", id: 2 },
      ],
    },
    length: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "ft", value: "ft", id: 1 },
        { label: "mtrs", value: "mtrs", id: 2 },
      ],
    },
    width: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "ft", value: "ft", id: 1 },
        { label: "mtrs", value: "mtrs", id: 2 },
      ],
    },
    totalHeight: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    axleHeightFromGround: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  constructionMaterials: {
    frameMaterial: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    frameCoating: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    frameCrossmemberType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    frameWeldType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    maximumAngleOfApproach: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    floorMaterial: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    sidesMaterial: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    roofMaterial: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  maintenanceFeatures: {
    greasePoints: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    bearingType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    maintenanceSchedule: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  userFeatures: {
    storage: { value: "", type: "radio", mandatory: false, radioOptions: null },
    tieDownPoints: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    toolBox: { value: "", type: "radio", mandatory: false, radioOptions: null },
    bumperType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  specialFeatures: {
    hydraulicTilt: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    extendableTongue: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    adjustableDeckHeight: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    detachableSidePanels: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  additionalAccessories: {
    rampType: { value: "", type: "radio", mandatory: true, radioOptions: null },
    winchPost: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    splashGuards: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    fenders: { value: "", type: "radio", mandatory: true, radioOptions: null },
    sideRails: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  customizationOptions: {
    color: { value: "", type: "radio", mandatory: true, radioOptions: null },
    decals: { value: "", type: "radio", mandatory: false, radioOptions: null },
    storageBox: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    lightingPackage: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    suspensionUpgrade: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  axlesAndSuspension: {
    axleType: { value: "", type: "radio", mandatory: true, radioOptions: null },
    axleCapacity: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "lbs", value: "lbs", id: 1 },
        { label: "Kgs", value: "Kgs", id: 2 },
      ],
    },
    axleSealType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    axleHubSize: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
    axlePosition: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    dropAxleOption: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    suspensionType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    suspensionCapacity: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "lbs", value: "lbs", id: 1 },
        { label: "Kgs", value: "Kgs", id: 2 },
      ],
    },
    suspensionAdjustment: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  tyresAndWheels: {
    tyreSize: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
    tyreLoadRange: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    tyreType: { value: "", type: "radio", mandatory: true, radioOptions: null },
    wheelType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    wheelBoltPattern: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    hubLubricationSystem: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  brakes: {
    brakeType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    brakeActuator: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    brakeLineMaterial: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    brakeDrumDiameter: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    brakeFluidType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    brakes: { value: "", type: "radio", mandatory: true, radioOptions: null },
    couplerSize: {
      value: "",
      type: "dual",
      mandatory: false,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
    couplerType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    couplerLockType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    hitchClass: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    hitchReceiverSize: {
      value: "",
      type: "dual",
      mandatory: false,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
    safetyChains: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    breakawaySystem: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  winchAndWrinchAccessories: {
    winchType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    winchCapacity: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "lbs", value: "lbs", id: 1 },
        { label: "Kbs", value: "Kbs", id: 2 },
      ],
    },
    winchRopeLength: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "ft", value: "ft", id: 1 },
        { label: "mtrs", value: "mtrs", id: 2 },
      ],
    },
    winchDrumMaterial: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchGearRatio: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchRemoteControl: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchBrakeType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchCableType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchStrapLength: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchHandleLength: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    winchMounting: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  lightingAndElectrical: {
    lighting: { value: "", type: "radio", mandatory: true, radioOptions: null },
    lightMountingPosition: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    lightType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    electricalConnectorType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    electricalWiringType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    batteryType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    batteryChargerType: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  acessories: {
    spareTyreCarrier: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    spareTyreSize: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
    spareTyreMountingLocation: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    jackType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    jackWheelType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    jackCapacity: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "lbs", value: "lbs", id: 1 },
        { label: "Kgs", value: "Kgs", id: 2 },
      ],
    },
    jackLiftHeight: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  loadingAndTransportFeatures: {
    loadingSystem: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "ft", value: "ft", id: 1 },
        { label: "mtrs", value: "mtrs", id: 2 },
      ],
    },
    bunks: { value: "", type: "radio", mandatory: false, radioOptions: null },
    bunkMaterial: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    bunkWidth: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    bunkHeightAdjustment: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    bunkMountingBracketMaterial: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    rollers: { value: "", type: "radio", mandatory: false, radioOptions: null },
    rollerMaterial: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    rollerAxleDiameter: {
      value: "",
      type: "dual",
      mandatory: false,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
  },
  securityFeatures: {
    wheelLocks: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    lockType: { value: "", type: "radio", mandatory: true, radioOptions: null },
    alarmSystem: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    gps_TrackingDevice: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
  },
  environmentalAndCorrosionResistance: {
    corrosionProtection: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    rustInhibitors: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  performanceAndHandling: {
    maximumSpeedRating: {
      value: "",
      type: "radio",
      mandatory: true,
      radioOptions: null,
    },
    turningRadius: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "ft", value: "ft", id: 1 },
        { label: "mtrs", value: "mtrs", id: 2 },
      ],
    },
  },
  tongue: {
    tongueMaterial: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    tongueShape: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    tongueJackWheelSize: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "cm", value: "cm", id: 1 },
        { label: "mm", value: "mm", id: 2 },
      ],
    },
    tongueJackType: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    tongueWeight: {
      value: "",
      type: "dual",
      mandatory: true,
      radioOptions: [
        { label: "Kg", value: "Kg", id: 1 },
        { label: "Ton", value: "Ton", id: 2 },
      ],
    },
    tongueWeightRatio: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  documentation: {
    ownerManual: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    warranty: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  regulatoryCompliance: {
    dot_Compliance: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    natmCertification: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    euTypeApproval: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    adrCompliance: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
  paymentTerms: {
    paymentTerms: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    currency: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    preferredPaymentMethod: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    invoiceAndRecieptProcedures: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    calculatePriceAndPay: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    priceLabel: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    priceDrop: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    VAT: { value: "", type: "radio", mandatory: false, radioOptions: null },
    totalPrice: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    country: { value: "", type: "radio", mandatory: false, radioOptions: null },
    globalAddressLookup: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    distance: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    contactDetails: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    uploadPhotos: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
    uploadVideos: {
      value: "",
      type: "radio",
      mandatory: false,
      radioOptions: null,
    },
  },
};

export const keyToExpectedValueMap = {
  grossVehicleWeightRating: "Gross Vehicle Weight Rating (GVWR)",
  ownerManual: "Owner’s Manual",
  tieDownPoints: "Tie-Down Points",
  VAT: "VAT",
  natmCertification: "NATM Certification",
  euTypeApproval: "EU Type Approval",
  adrCompliance: "ADR Compliance",
};
