export const typeDef = {
  identification: {
    trailerId: { value: "", type: "radio", mandatory: true },
    manufacturer: { value: "", type: "radio", mandatory: true },
    make: { value: "", type: "radio", mandatory: true },
    model: { value: "", type: "radio", mandatory: true },
    year: { value: "", type: "radio", mandatory: true },
    askingPrice: { value: "", type: "radio", mandatory: true },
  },
  basics: {
    type: { value: "", type: "radio", mandatory: true },
    gvwr: { value: "", type: "radio", mandatory: true },
    loadCapacity: { value: "", type: "radio", mandatory: true },
    length: { value: "", type: "radio", mandatory: true },
    width: { value: "", type: "radio", mandatory: true },
    totalHeight: { value: "", type: "radio", mandatory: true },
    axleHeightFromGround: { value: "", type: "radio", mandatory: true },
  },
  constructionMaterials: {
    frameMaterial: { value: "", type: "radio", mandatory: true },
    frameCoating: { value: "", type: "radio", mandatory: true },
    frameCrossmemberType: { value: "", type: "radio", mandatory: true },
    frameWeldType: { value: "", type: "radio", mandatory: false },
    maximumAngleOfApproach: { value: "", type: "radio", mandatory: false },
    floorMaterial: { value: "", type: "radio", mandatory: true },
    sidesMaterial: { value: "", type: "radio", mandatory: true },
    roofMaterial: { value: "", type: "radio", mandatory: true },
  },
  maintenanceFeatures: {
    greasePoints: { value: "", type: "radio", mandatory: false },
    bearingType: { value: "", type: "radio", mandatory: false },
    maintenanceSchedule: { value: "", type: "radio", mandatory: false },
  },
  userFeatures: {
    storage: { value: "", type: "radio", mandatory: false },
    tieDownPoints: { value: "", type: "radio", mandatory: true },
    toolBox: { value: "", type: "radio", mandatory: false },
    bumperType: { value: "", type: "radio", mandatory: false },
  },
  specialFeatures: {
    hydraulicTilt: { value: "", type: "radio", mandatory: true },
    extendableTongue: { value: "", type: "radio", mandatory: true },
    adjustableDeckHeight: { value: "", type: "radio", mandatory: false },
    detachableSidePanels: { value: "", type: "radio", mandatory: false },
  },
  additionalAccessories: {
    rampType: { value: "", type: "radio", mandatory: true },
    winchPost: { value: "", type: "radio", mandatory: true },
    splashGuards: { value: "", type: "radio", mandatory: true },
    fenders: { value: "", type: "radio", mandatory: true },
    sideRails: { value: "", type: "radio", mandatory: true },
  },
  customizationOptions: {
    color: { value: "", type: "radio", mandatory: true },
    decals: { value: "", type: "radio", mandatory: false },
    storageBox: { value: "", type: "radio", mandatory: false },
    lightingPackage: { value: "", type: "radio", mandatory: false },
    suspensionUpgrade: { value: "", type: "radio", mandatory: false },
  },
  axlesAndSuspension: {
    axleType: { value: "", type: "radio", mandatory: true },
    axleCapacity: { value: "", type: "radio", mandatory: true },
    axleSealType: { value: "", type: "radio", mandatory: false },
    axleHubSize: { value: "", type: "radio", mandatory: true },
    axlePosition: { value: "", type: "radio", mandatory: true },
    dropAxleOption: { value: "", type: "radio", mandatory: false },
    suspensionType: { value: "", type: "radio", mandatory: true },
    suspensionCapacity: { value: "", type: "radio", mandatory: true },
    suspensionAdjustment: { value: "", type: "radio", mandatory: true },
  },
  tyresAndWheels: {
    tyreSize: { value: "", type: "radio", mandatory: true },
    tyreLoadRange: { value: "", type: "radio", mandatory: true },
    tyreType: { value: "", type: "radio", mandatory: true },
    wheelType: { value: "", type: "radio", mandatory: true },
    wheelBoltPattern: { value: "", type: "radio", mandatory: false },
    hubLubricationSystem: { value: "", type: "radio", mandatory: false },
  },
  brakes: {
    brakeType: { value: "", type: "radio", mandatory: false },
    brakeActuator: { value: "", type: "radio", mandatory: false },
    brakeLineMaterial: { value: "", type: "radio", mandatory: true },
    brakeDrumDiameter: { value: "", type: "radio", mandatory: true },
    brakeFluidType: { value: "", type: "radio", mandatory: true },
    brakes: { value: "", type: "radio", mandatory: true },
    couplerSize: { value: "", type: "radio", mandatory: false },
    couplerType: { value: "", type: "radio", mandatory: true },
    couplerLockType: { value: "", type: "radio", mandatory: true },
    hitchClass: { value: "", type: "radio", mandatory: true },
    hitchReceiverSize: { value: "", type: "radio", mandatory: false },
    safetyChains: { value: "", type: "radio", mandatory: true },
    breakawaySystem: { value: "", type: "radio", mandatory: true },
  },
  winchAndWrinchAccessories: {
    winchType: { value: "", type: "radio", mandatory: true },
    winchCapacity: { value: "", type: "radio", mandatory: true },
    winchRopeLength: { value: "", type: "radio", mandatory: true },
    winchDrumMaterial: { value: "", type: "radio", mandatory: false },
    winchGearRatio: { value: "", type: "radio", mandatory: false },
    winchRemoteControl: { value: "", type: "radio", mandatory: false },
    winchBrakeType: { value: "", type: "radio", mandatory: false },
    winchCableType: { value: "", type: "radio", mandatory: false },
    winchStrapLength: { value: "", type: "radio", mandatory: false },
    winchHandleLength: { value: "", type: "radio", mandatory: false },
    winchMounting: { value: "", type: "radio", mandatory: false },
  },
  lightingAndElectrical: {
    lighting: { value: "", type: "radio", mandatory: true },
    lightMountingPosition: { value: "", type: "radio", mandatory: false },
    lightType: { value: "", type: "radio", mandatory: true },
    electricalConnectorType: { value: "", type: "radio", mandatory: true },
    electricalWiringType: { value: "", type: "radio", mandatory: true },
    batteryType: { value: "", type: "radio", mandatory: true },
    batteryChargerType: { value: "", type: "radio", mandatory: true },
  },
  acessories: {
    spareTyreCarrier: { value: "", type: "radio", mandatory: true },
    spareTyreSize: { value: "", type: "radio", mandatory: true },
    spareTyreMountingLocation: { value: "", type: "radio", mandatory: false },
    jackType: { value: "", type: "radio", mandatory: false },
    jackWheelType: { value: "", type: "radio", mandatory: false },
    jackCapacity: { value: "", type: "radio", mandatory: true },
    jackLiftHeight: { value: "", type: "radio", mandatory: false },
  },
  loadingAndTransportFeatures: {
    loadingSystem: { value: "", type: "radio", mandatory: true },
    bunks: { value: "", type: "radio", mandatory: false },
    bunkMaterial: { value: "", type: "radio", mandatory: false },
    bunkWidth: { value: "", type: "radio", mandatory: false },
    bunkHeightAdjustment: { value: "", type: "radio", mandatory: false },
    bunkMountingBracketMaterial: { value: "", type: "radio", mandatory: false },
    rollers: { value: "", type: "radio", mandatory: false },
    rollerMaterial: { value: "", type: "radio", mandatory: false },
    rollerAxleDiameter: { value: "", type: "radio", mandatory: false },
  },
  securityFeatures: {
    wheelLocks: { value: "", type: "radio", mandatory: true },
    lockType: { value: "", type: "radio", mandatory: true },
    alarmSystem: { value: "", type: "radio", mandatory: true },
    gpsTrackingDevice: { value: "", type: "radio", mandatory: true },
  },
  environmentalAndCorrosionResistance: {
    corrosionProtection: { value: "", type: "radio", mandatory: true },
    rustInhibitors: { value: "", type: "radio", mandatory: false },
  },
  performanceAndHandling: {
    maximumSpeedRating: { value: "", type: "radio", mandatory: true },
    turningRadius: { value: "", type: "radio", mandatory: true },
  },
  tongue: {
    tongueMaterial: { value: "", type: "radio", mandatory: false },
    tongueShape: { value: "", type: "radio", mandatory: false },
    tongueJackWheelSize: { value: "", type: "radio", mandatory: true },
    tongueJackType: { value: "", type: "radio", mandatory: false },
    tongueWeight: { value: "", type: "radio", mandatory: true },
    tongueWeightRatio: { value: "", type: "radio", mandatory: false },
  },
  documentation: {
    ownerManual: { value: "", type: "radio", mandatory: false },
    warranty: { value: "", type: "radio", mandatory: false },
  },
  regulatoryCompliance: {
    dotCompliance: { value: "", type: "radio", mandatory: false },
    natmCertification: { value: "", type: "radio", mandatory: false },
    euTypeApproval: { value: "", type: "radio", mandatory: false },
    adrCompliance: { value: "", type: "radio", mandatory: false },
  },
  paymentTerms: {
    paymentTerms: { value: "", type: "radio", mandatory: false },
    currency: { value: "", type: "radio", mandatory: false },
    preferredPaymentMethod: { value: "", type: "radio", mandatory: false },
    invoiceAndRecieptProcedures: { value: "", type: "radio", mandatory: false },
    calculatePriceAndPay: { value: "", type: "radio", mandatory: false },
    priceLabel: { value: "", type: "radio", mandatory: false },
    priceDrop: { value: "", type: "radio", mandatory: false },
    VAT: { value: "", type: "radio", mandatory: false },
    totalPrice: { value: "", type: "radio", mandatory: false },
    country: { value: "", type: "radio", mandatory: false },
    globalAddressLookup: { value: "", type: "radio", mandatory: false },
    distance: { value: "", type: "radio", mandatory: false },
    contactDetails: { value: "", type: "radio", mandatory: false },
    uploadPhotos: { value: "", type: "radio", mandatory: false },
    uploadVideos: { value: "", type: "radio", mandatory: false },
  },
};

export const keyToExpectedValueMap = {
  grossVehicleWeightRating: "Gross Vehicle Weight Rating (GVWR)",
  ownerManual: "Owner’s Manual",
  tieDownPoints: "Tie-Down Points",
  gpsTrackingDevice: "GPS Tracking Device",
  VAT: "VAT",
  dotCompliance: "DOT Compliance",
  natmCertification: "NATM Certification",
  euTypeApproval: "EU Type Approval",
  adrCompliance: "ADR Compliance",
};
