export const keyToExpectedValueMap = {
  specialRequirementsRequests: "Special Requirements/Requests",
  petFriendlyPolicy: "Pet-Friendly Policy",
  additionalFees: "Additional Fees (e.g., Docking Fees, Port Taxes)",
  lateCheckInOutFees: "Late Check-In/Check-Out Fees",
  vat: "VAT (Value Added Tax)",
};

export const typeDef = {
  guestAccomodation: {
    marisailVesselId: { value: "", type: "radio", mandatory: true },
    marisailCharterId: { value: "", type: "radio", mandatory: true },
    guestCapacity: { value: "", type: "radio", mandatory: true },
    bedroomConfiguration: { value: "", type: "radio", mandatory: true },
    bathroomConfiguration: { value: "", type: "radio", mandatory: true },
    crewAccommodations: { value: "", type: "radio", mandatory: true },
    accessibilityInformation: { value: "", type: "radio", mandatory: true },
    cleaningAndMaintenanceProcedures: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    vesselDecorAndSetupRequests: { value: "", type: "radio", mandatory: true },
  },
  locationDetails: {
    boardingPortArrivalTime: { value: "", type: "radio", mandatory: true },
    boardingPortDepartureTime: { value: "", type: "radio", mandatory: true },
    summerCruisingAreas: { value: "", type: "radio", mandatory: true },
    boardingPort: { value: "", type: "radio", mandatory: true },
    winterCruisingAreas: { value: "", type: "radio", mandatory: true },
    disembarkationPort: { value: "", type: "radio", mandatory: true },
    embarkationAndDisembarkationLogistics: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    disembarkationPortArrivalTime: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    dockingAndMooringInstructions: {
      value: "",
      type: "radio",
      mandatory: true,
    },
  },
  guestRequirements: {
    skipperIncluded: { value: "", type: "radio", mandatory: true },
    crewIncluded: { value: "", type: "radio", mandatory: true },
    crewUniformPreferences: { value: "", type: "radio", mandatory: true },
    localCuisinePreferences: { value: "", type: "radio", mandatory: true },
    cateringRequired: { value: "", type: "radio", mandatory: true },
    carParkingAvailable: { value: "", type: "radio", mandatory: true },
    specialRequirementsRequests: { value: "", type: "radio", mandatory: true },
  },
  charterAgreementTermsAndConditions: {
    smokingPolicy: { value: "", type: "radio", mandatory: true },
    petFriendlyPolicy: { value: "", type: "radio", mandatory: true },
    localRegulationsAndRestrictions: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    charterAgreementTermsAndConditions: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    environmentalPolicies: { value: "", type: "radio", mandatory: true },
    waterConservationMeasures: { value: "", type: "radio", mandatory: true },
    wasteManagementProtocols: { value: "", type: "radio", mandatory: true },
    alcoholPolicy: { value: "", type: "radio", mandatory: true },
    photographyAndVideographyPolicies: {
      value: "",
      type: "radio",
      mandatory: true,
    },
  },
  guestSafety: {
    weatherContingencyPlans: { value: "", type: "radio", mandatory: true },
    emergencyProcedures: { value: "", type: "radio", mandatory: true },
    medicalFacilitiesOnboard: { value: "", type: "radio", mandatory: true },
    emergencyContacts: { value: "", type: "radio", mandatory: true },
    weatherForecastServices: { value: "", type: "radio", mandatory: true },
    securityMeasures: { value: "", type: "radio", mandatory: true },
    guestOrientationAndSafetyBriefing: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    insuranceGuestsAndPersonalBelongings: {
      value: "",
      type: "radio",
      mandatory: true,
    },
    insuranceCoverageDetails: { value: "", type: "radio", mandatory: true },
  },
  costs: {
    summerRatePerNight: { value: "", type: "radio", mandatory: true },
    winterRatePerWeek: { value: "", type: "radio", mandatory: true },
    winterRatePerNight: { value: "", type: "radio", mandatory: true },
    summerRatePerWeek: { value: "", type: "radio", mandatory: true },
    securityDepositAmount: { value: "", type: "radio", mandatory: true },
    totalPrice: { value: "", type: "radio", mandatory: true },
    refundableDeposit: { value: "", type: "radio", mandatory: true },
    additionalFuelCosts: { value: "", type: "radio", mandatory: true },
    additionalFees: { value: "", type: "radio", mandatory: true },
    fuelIncluded: { value: "", type: "radio", mandatory: true },
    lateCheckInOutFees: { value: "", type: "radio", mandatory: true },
    vat: { value: "", type: "radio", mandatory: true },
  },
  availableDates: {
    minimumNightsPolicy: { value: "", type: "radio", mandatory: true },
    datesAvailable: { value: "", type: "radio", mandatory: true },
    cancellationPolicy: { value: "", type: "radio", mandatory: true },
  },
  dates: {
    startDate: { value: "", type: "radio", mandatory: true },
    endDate: { value: "", type: "radio", mandatory: true },
    numberNights: { value: "", type: "radio", mandatory: true },
  },
  paymentTerms: {
    paymentTerms: { value: "", type: "radio", mandatory: true },
    currency: { value: "", type: "radio", mandatory: true },
    preferredPaymentMethods: { value: "", type: "radio", mandatory: true },
    invoiceAndReceiptProcedures: { value: "", type: "radio", mandatory: true },
    calculatePriceAndPay: { value: "", type: "radio", mandatory: true },
    priceLabel: { value: "", type: "radio", mandatory: true },
    priceDrop: { value: "", type: "radio", mandatory: true },
  },
};
