export const AUCTION_ADVERT = [
  { key: "boatDetails", columnName: "Boat_Details", tableName: "Auction" },
  { key: "lotNumber", columnName: "Lot_Number", tableName: "Auction" },
  { key: "descriptionOfItemProperty", columnName: "Description", tableName: "Auction" },
  { key: "auctionStatus", columnName: "Auction_Status", tableName: "Auction" },
  { key: "conditionsOfSale", columnName: "Conditions_of_Sale", tableName: "Auction" },
  { key: "auctioneerContactInformation", columnName: "Auctioneer_Contact_Information", tableName: "Auction" },
  { key: "resultsOrOutcome", columnName: "Results_or_Outcome", tableName: "Auction" },
  { key: "sellerInformation", columnName: "Seller_Information", tableName: "Auction" },
  { key: "auctionDetails", columnName: "Auction_Details", tableName: "Auction" },
  { key: "marisailAuctionId", columnName: "Auction_Number", tableName: "Auction" },
  { key: "auctionDate", columnName: "Auction_Date", tableName: "Auction" },
  { key: "auctionVenue", columnName: "Auction_Venue", tableName: "Auction" },
  { key: "startTime", columnName: "Closing_Time", tableName: "Auction" },
  { key: "closingTime", columnName: "Closing_Time", tableName: "Auction" },
  { key: "biddingPeriod", columnName: "Bidding_Period", tableName: "Auction" },
  { key: "inspectionPeriod", columnName: "Inspection_Period", tableName: "Auction" },
  { key: "inspection", columnName: "Inspection", tableName: "Auction" },
  { key: "withdrawalDeadline", columnName: "Withdrawal_Deadline", tableName: "Auction" },
  { key: "postAuctionSettlementPeriod", columnName: "PostAuction_Settlement_Period", tableName: "Auction" },
  { key: "bidPrice", columnName: "Starting_Bid", tableName: "Bid" },
  { key: "bidTimestamp", columnName: "Starting_Bid", tableName: "Bid" },
  { key: "startingBid", columnName: "Starting_Bid", tableName: "Bid" },
  { key: "bidIncrement", columnName: "Bid_Increment", tableName: "Bid" },
  { key: "openingBid", columnName: "Opening_Bid", tableName: "Bid" },
  { key: "minimumBid", columnName: "Minimum_Bid", tableName: "Bid" },
  { key: "winningBid", columnName: "Winning_Bid", tableName: "Bid" },
  { key: "reservePriceBuyItNow", columnName: "Reserve_Price", tableName: "Bid" },
  { key: "sellersReserveStatus", columnName: "Sellers_Reserve_Status", tableName: "Bid" },
  { key: "highestBidder", columnName: "Highest_Bidder", tableName: "Bid" },
  { key: "bidderRegistrationRequirements", columnName: "Bidder_Registration_Requirements", tableName: "Bid" },
  { key: "marisailBidderId", columnName: "Marisail_Bidder_ID", tableName: "Bid" },
  { key: "numberBidders", columnName: "Buyers_Premium", tableName: "Bid" },
  { key: "buyersPremium", columnName: "Buyers_Premium", tableName: "Bid" },
  { key: "paymentTerms", columnName: "Payment_Terms", tableName: "Auction_Payment" },
  { key: "currency", columnName: "Currency", tableName: "Auction_Payment" },
  { key: "preferredPaymentMethods", columnName: "Preferred_Payment", tableName: "Auction_Payment" },
  { key: "invoiceReceiptProcedures", columnName: "Invoice_Receipt", tableName: "Auction_Payment" },
  { key: "calculatePricePay", columnName: "Calculate", tableName: "Auction_Sales" },
  { key: "priceLabel", columnName: "Price_Label", tableName: "Auction_Sales" },
  { key: "priceDrop", columnName: "Price_Drop", tableName: "Auction_Sales" },
  { key: "vat", columnName: "VAT", tableName: "Auction_Sales" },
  { key: "totalPrice", columnName: "Total_Price", tableName: "Auction_Sales" }
]


export const UNIQUE_TABLE = [
  "Auction",
  "Bid",
  "Auction_Payment",
  "Auction_Sales",
];
