export const varToColumn = {
    // Site Details
    marisailBerthId: "Marisail_Berth_ID",
    dataSource: "Data Source",
    siteDetails: "Site_Details",
    termsAndConditions: "Terms_Conditions",
    type: "Type",
    marinaName: "Name",
    location: "Location",
    ownership: "Ownership",
    yearEstablished: "Year_Established",
    operatingHours: "Operating_Hours",
    contactDetails: "Contact",
    seasonalOperation: "Seasonal_Operation",
    languageServices: "Language",

    // General Information
    dockTypes: "Dock_Types",
    numberOfDocks: "Number_Docks",
    boatSlipSizes: "Slip_Sizes",
    // location: "Location",
    numberOfBerthsAvailable: "Berths_Available",
    length: "Length",
    beam: "Beam",
    draft: "Draft",
    slipWidth: "Slip_Width",
    slipLength: "Slip_Length",
    mooringType: "Mooring_Type",
    tideRange: "Tide_Range",

    // Amenities & Services
    storage: "Storage",
    electricityAvailable: "Electricity_Available",
    waterSupply: "Water_Supply",
    wifiAvailability: "WiFi_Availability",
    carParking: "Car_Parking",
    conciergeServices: "Concierge",
    businessServices: "Business",
    conferenceRooms: "Conference_Rooms",
    
    // Family Facilities
    laundryFacilities: "Laundry_Facilities",
    restaurantsAndCafes: "Restaurants_Cafes",
    restaurant: "Restaurant",
    bar: "Bar",
    shoppingFacilities: "Shopping_Facilities",
    retailShops: "Retail_Shops",
    hospitalityServices: "Hospitality",
    recreationalFacilities: "Recreational Facilities",
    // conciergeServices: "Concierge Services",
    clubhouseAccess: "Clubhouse_Access",
    swimmingPool: "Swimming_Pool",
    fitnessCenter: "Fitness_Center",
    marinaStore: "Marina_Store",
    chandlery: "Chandlery",
    restroomAndShowers: "Restroom_Showers",
    laundryServices: "Laundry",
    gymFacilities: "Gym_Facilities",
    sanitationnFacilities: "Sanitation_Facilities",
    guestAccomodationOptions: "Guest_Accomodation_Options",
    familyFriendlyAmenities: "Family_Friendly",
    petFriendlyServices: "Pet_Friendly",
    iceAvailability: "Ice_Availability",
    picnicAndBBQAreas: "Picnic_BBQ",
    childrensPlayArea: "Childrens_Play",

    // Surrounding Area
    localAttractions: "Local_Attractions",
    restaurants: "Restaurants",
    accommodation: "Accommodation",
    shopping: "Shopping",
    transportationOptions: "Transportation",
    medicalFacilitesNearby: "Medical_Facilities",
    localServices: "Local",
    communityResources: "Community_Resources",

    // Additional Features
    charterServices: "Charter",
    yachtBrokerageServices: "Yacht_Brokerage",
    boatShowParticipation: "Boat_Show",
    loyaltyPrograms: "Loyalty_Programs",
    referralPrograms: "Referral_Programs",
    vipMembershipOptions: "VIP_Membership",

    // Community & Social
    annualEvents: "Annual_Events",
    educationalPrograms: "Educational_Programs",
    communityEvents: "Community_Events",
    socialEvents: "Social_Events",
    sportsActivities: "Sports_Activities",
    culturalEvents: "Cultural_Events",
    seasonalActivities: "Seasonal_Activities",
    yachtClubMembership: "Club_Membership",
    // socialEvents: "Social Events",
    regattasAndCompetitions: "Regattas",
    workshopsAndClasses: "Workshops_Classes",
    communityBulletinBoard: "Bulletin_Board",
    networkingEvents: "Networking_Events",
    memberDiscounts: "Member_Discounts",

    // Services
    pumpOutStation: "Pump_Station",
    docksideTrolley: "Dockside_Trolley",
    powerSupply: "Power_Supply",
    // waterSupply: "Water Supply",
    shorePowerConnectionTypes: "Power_Connection",
    fuelTypesAvailable: "Fuel_Types",
    fuelService: "Fuel_Service",
    fuelDock: "Fuel_Dock",
    electricalHookupSpecifications: "Electrical_Hookup",

    // Repair & Maintenance
    boatYardServices: "Yard",
    boatCleaningServices: "Boat_Cleaning",
    boatMaintenanceAndRepair: "Maintenance_Repair",
    chandleryServices: "Chandlery",
    repairAndMaintenanceServices: "Maintenance",
    haulOutServices: "HaulOut",
    boatLiftSpecifications: "Boat_Lift",

    // Accessibility
    handicapAccessibleSlips: "Handicap_Slips",
    proximityToHandicapParking: "Proximity_Parking",
    accessibleFacilities: "Accessible_Facilities",
    assistanceServicesForDisabled: "Assistance",
    signageAndDirections: "Signage_Directions",
    accessibleRestroomsAndShowers: "Accessible_Restrooms",
    parkingFacilities: "Parking_Facilities",
    accessibilityFeatures: "Accessibility_Features",
    disabledAccessFacilities: "Disabled_Facilities",
    publicTransportationLinks: "Transportation_Links",


    // Connectivity & Transportation
    shuttleServices: "Shuttle",
    transportServices: "Transport",
    transportLinks: "Transport_Links",
    nearbyAirports: "Nearby_Airports",
    publicTransportLinks: "Public_Transport_Links",
    taxiServices: "Taxi",
    bikeRentals: "Bike_Rentals",
    proximityToNearbyAttractions: "Nearby_Attractions",
    carRentalServices: "Car_Rental",
    airportTransferServices: "Airport_Transfer",

    // Environmental Considerations
    environmentalCertifications: "Environmental_Certifications",
    wasteDisposal: "Waste_Disposal",
    wasteManagementPolicies: "Waste_Management",
    waterQualityMonitoring: "Water_Quality",
    wasteDisposalServices: "Waste_Disposal",
    waterTreatmentSystems: "Water_Treatment",
    waterConservationMeasures: "Water_Conservation",
    waterHookupSpecifications: "Water_Hookup",
    recyclingPrograms: "Recycling_Programs",
    ecoFriendlyCleaningProducts: "EcoCleaning_Products",
    pollutionControlMeasures: "Pollution_Control",
    wildlifeConservationEfforts: "Wildlife_Conservation",
    greenBuildingCertifications: "Building_Certifications",
    energySources: "Energy_Sources",
    // environmentalCertifications: "Environmental_Certifications",
    marineLifeProtectionMeasures: "Marine_Life",
    greenCertifications: "Green_Certifications",
    // recyclingPrograms: "Recycling_Programs",
    ecoFriendlyProductsAvailability: "Eco_Friendly_Products",
    sewageTreatmentPlants: "Sewage_Treatment",

    // Security & Safety
    fireSafetySystems: "Fire_Safety",
    emergencyContactInformation: "Emergency_Contact",
    emergencyMedicalServices: "Emergency_Medical",
    emergencyEvacuationPlans: "Emergency_Evacuation",
    // emergencyContactInformation: "Emergency_Contact",
    fireSafetyEquipment: "Fire _Safety",
    firstAidKits: "First_Aid",
    evacuationPlan: "Evacuation_Plan",
    navigationAssistance: "Navigation_Assistance",
    navigationAids: "Navigation_Aids",
    pilotageServices: "Pilotage",
    harborEntranceDepth: "Harbor_Entrance_Depth",
    tideInformationServices: "Tide",
    dockingDepths: "Docking_Depths",
    marinaBasinDepth: "Marina_Basin",
    waveProtectionMeasures: "Wave_Protection",
    weatherMonitoringServices: "Weather_Monitoring",
    shelterAndProtection: "Shelter_Protection",
    prevailingWinds: "Prevailing_Winds",
    seaConditions: "Sea_Conditions",
    breakwaterTypes: "Breakwater_Types",
    weatherShelters: "Weather_Shelters",
    stormPreparationServices: "Storm_Preparation",
    floatingDockAvailability: "Floating_Dock",
    safetyInspections: "Safety_Inspections",
    dockConstructionMaterial: "Dock_Construction",
    pileAnchoringSystem: "Pile_Anchoring_System",
    dockMaterial: "Dock_Material",
    security: "Security",
    securityPatrol: "Security_Patrol",
    cctvSurveillance: "CCTV_Surveillance",
    accessControlSystems: "Access_Control",
    securityLighting: "Security_Lighting",

    // Legal & Compliance
    permitsAndLicenses: "Permits_Licenses",
    customsAndImmigration: "Customs_Immigration",
    healthAndSafetyRegulations: "Health_Safety",
    environmentalRegulationsCompliance: "Environmental_Compliance",
    portStateControlInspections: "Port_Control",
    quarantineServices: "Quarantine",

    // Insurance & Regulations
    insuranceRequirements: "Insurance",
    liabilityInsuranceRequirements: "Liability_Insurance",
    proofOfOwnershipRequired: "POO_Required",
    complianceWithLocalRegulations: "Local_Compliance",
    // safetyInspections: "Safety_Inspections",
    certificateOfSeaworthiness: "Seaworthiness_Certificate",
    dockUseRegulations: "Dock_Use",
    environmentalComplianceCertificates: "Environmental_Compliance",
    
    // Financial Information
    currency: "Currency",
    mooringFees: "Mooring_Fees",
    serviceCharges: "Service_Charges",
    membershipPrograms: "Membership_Programs",
    paymentMethods: "Payment_Methods",
    pricingStructure: "Pricing_Structure",
    depositRequirements: "Deposit",
    cancellationPolicies: "Cancellation_Policies",  
    discountsAvailable: "Discounts_Available",

    // Pricing & Lease Terms
    pricePerAnnum: "Price_PA",
    pricePerMonth: "Price_PCM",
    pricePerWeek: "Price_PW",
    availability: "Availability",
    annualLeaseRenewable: "Lease_Renewable",
    cancellationPolicy: "Cancellation_Policy",
    latePaymentFees: "Late_Fees",
    // insuranceRequirements: "Insurance",

    // Payment Terms
    paymentTerms: "Payment_Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred_Payment",
    invoiceAndReceiptProcedures: "Invoice_Receipt",
    
    // Calculate Price & Pay
    calculatePriceAndPay: "Calculate",
    priceLabel: "Price_Label",
    priceDrop: "Price_Drop",
    // currency: "Currency",
    vat: "VAT",
    // totalPrice: "Total Price",

    // Country (Lying)
    // country: "Country (Lying)",
    // addressDetails: "Address Details",
    // distance: "Distance",
    // contactDetails: "Contact Details",
    // uploadPhotos: "Upload Photos",
    // uploadVideos: "Upload Videos",
}

export const varToTable = {
    siteDetails: "Marina_Port",
    generalInformation: "Berths",
    amenitiesAndServices: "Amenities",
    familyFacilities: "Family",
    surroundingArea: "Local_Area",
    additionalFeatures: "Berth_Features",
    communityAndSocial: "Events",
    services: "Operations",
    repairAndMaintenance: "Repairs",
    accessibility: "Accessibility",
    connectivityAndTransportation: "Connectivity",
    environmentalConsiderations: "Environment",
    securityAndSafety: "Safety_Procedures",
    legalAndCompliance: "Legal",
    insuranceAndRegulations: "Insurance",
    financialInformation: "Financial",
    pricingAndLeaseTerms: "Pricing",    
    paymentTerms: "Berth_Payment",
    calculatePriceAndPay: "Berth_Sales",
}

export const uniqueTable = [
    "Marina_Port",
    "Berths",
    "Amenities",
    "Family",
    "Local_Area",
    "Berth_Features",
    "Events",
    "Operations",
    "Repairs",
    "Accessibility",
    "Connectivity",
    "Environment",
    "Safety_Procedures",
    "Legal",
    "Insurance",
    "Financial",
    "Pricing",
    "Berth_Payment",
    "Berth_Sales",
]

