export const BERTHS_ADVERT = [
  { key: "marisailBerthId", columnName: "Marisail_Berth_ID", tableName: "Marina_Port" },
  { key: "siteDetails", columnName: "Site_Details", tableName: "Marina_Port" },
  { key: "termsAndConditions", columnName: "Terms_Conditions", tableName: "Marina_Port" },
  { key: "type", columnName: "Type", tableName: "Marina_Port" },
  { key: "marinaPortHarborName", columnName: "Name", tableName: "Marina_Port" },
  { key: "location", columnName: "Location", tableName: "Marina_Port" },
  { key: "ownership", columnName: "Ownership", tableName: "Marina_Port" },
  { key: "yearEstablished", columnName: "Year_Established", tableName: "Marina_Port" },
  { key: "operatingHours", columnName: "Operating_Hours", tableName: "Marina_Port" },
  { key: "contactDetails", columnName: "Contact", tableName: "Marina_Port" },
  { key: "seasonalOperation", columnName: "Seasonal_Operation", tableName: "Marina_Port" },
  { key: "languageServices", columnName: "Language", tableName: "Marina_Port" },

  { key: "dockTypes", columnName: "Dock_Types", tableName: "Berths" },
  { key: "numberOfDocks", columnName: "Number_Docks", tableName: "Berths" },
  { key: "boatSlipSizes", columnName: "Slip_Sizes", tableName: "Berths" },
  { key: "location", columnName: "Location", tableName: "Berths" },
  { key: "numberBerthsAvailable", columnName: "Berths_Available", tableName: "Berths" },
  { key: "length", columnName: "Length", tableName: "Berths" },
  { key: "beam", columnName: "Beam", tableName: "Berths" },
  { key: "draft", columnName: "Draft", tableName: "Berths" },
  { key: "slipWidth", columnName: "Slip_Width", tableName: "Berths" },
  { key: "slipDepth", columnName: "Slip_Depth", tableName: "Berths" },
  { key: "slipLength", columnName: "Slip_Length", tableName: "Berths" },
  { key: "mooringType", columnName: "Mooring_Type", tableName: "Berths" },
  { key: "tideRange", columnName: "Tide_Range", tableName: "Berths" },

  { key: "storage", columnName: "Storage", tableName: "Amenities" },
  { key: "electricityAvailable", columnName: "Electricity_Available", tableName: "Amenities" },
  { key: "waterSupply", columnName: "Water_Supply", tableName: "Amenities" },
  { key: "wiFiAvailability", columnName: "WiFi_Availability", tableName: "Amenities" },
  { key: "carParking", columnName: "Car_Parking", tableName: "Amenities" },
  { key: "conciergeServices", columnName: "Concierge", tableName: "Amenities" },
  { key: "businessServices", columnName: "Business", tableName: "Amenities" },
  { key: "conferenceRooms", columnName: "Conference_Rooms", tableName: "Amenities" },

  { key: "laundryFacilities", columnName: "Laundry_Facilities", tableName: "Family" },
  { key: "restaurantsAndCafes", columnName: "Restaurants_Cafe", tableName: "Family" },
  { key: "restaurant", columnName: "Restaurant", tableName: "Family" },
  { key: "bar", columnName: "Bar", tableName: "Family" },
  { key: "shoppingFacilities", columnName: "Shopping_Facilities", tableName: "Family" },
  { key: "retailShops", columnName: "Retail_Shops", tableName: "Family" },
  { key: "hospitalityServices", columnName: "Hospitality", tableName: "Family" },
  { key: "recreationalFacilities", columnName: "Recreational_Facilities", tableName: "Family" },
  { key: "conciergeServices", columnName: "Concierge", tableName: "Family" },
  { key: "clubhouseAccess", columnName: "Clubhouse_Access", tableName: "Family" },
  { key: "swimmingPool", columnName: "Swimming_Pool", tableName: "Family" },
  { key: "fitnessCenter", columnName: "Fitness_Center", tableName: "Family" },
  { key: "marinaStore", columnName: "Marina_Store", tableName: "Family" },
  { key: "chandlery", columnName: "Chandlery", tableName: "Family" },
  { key: "restroomsAndShowers", columnName: "Restrooms_Showers", tableName: "Family" },
  { key: "laundryServices", columnName: "Laundry", tableName: "Family" },
  { key: "gymFacilities", columnName: "Gym_Facilities", tableName: "Family" },
  { key: "sanitationFacilities", columnName: "Sanitation_Facilities", tableName: "Family" },
  { key: "guestAccommodationOptions", columnName: "Guest_Accommodation_Options", tableName: "Family" },
  { key: "familyFriendlyAmenities", columnName: "Family_Friendly", tableName: "Family" },
  { key: "petFriendlyServices", columnName: "Pet_Friendly", tableName: "Family" },
  { key: "iceAvailability", columnName: "Ice_Availability", tableName: "Family" },
  { key: "picnicAndBBQAreas", columnName: "Picnic_BBQ", tableName: "Family" },
  { key: "childrensPlayArea", columnName: "Childrens_Play", tableName: "Family" },

  { key: "localAttractions", columnName: "Local_Attractions", tableName: "Local_Area" },
  { key: "restaurants", columnName: "Restaurants", tableName: "Local_Area" },
  { key: "accommodation", columnName: "Accommodation", tableName: "Local_Area" },
  { key: "shopping", columnName: "Shopping", tableName: "Local_Area" },
  { key: "transportationOptions", columnName: "Transportation", tableName: "Local_Area" },
  { key: "medicalFacilitiesNearby", columnName: "Medical_Facilities", tableName: "Local_Area" },
  { key: "localServices", columnName: "Local", tableName: "Local_Area" },
  { key: "communityResources", columnName: "Community_Resources", tableName: "Local_Area" },

  { key: "charterServices", columnName: "Charter", tableName: "Berth_Features" },
  { key: "yachtBrokerageServices", columnName: "Yacht_Brokerage", tableName: "Berth_Features" },
  { key: "boatShowParticipation", columnName: "Boat_Show", tableName: "Berth_Features" },
  { key: "loyaltyPrograms", columnName: "Loyalty_Programs", tableName: "Berth_Features" },
  { key: "referralPrograms", columnName: "Referral_Programs", tableName: "Berth_Features" },
  { key: "vip_MembershipOptions", columnName: "VIP_Membership", tableName: "Berth_Features" },

  { key: "annualEvents", columnName: "Annual_Events", tableName: "Events" },
  { key: "educationalPrograms", columnName: "Educational_Programs", tableName: "Events" },
  { key: "communityEvents", columnName: "Community_Events", tableName: "Events" },
  { key: "socialEvents", columnName: "Social_Events", tableName: "Events" },
  { key: "sportsActivities", columnName: "Sports_Activities", tableName: "Events" },
  { key: "culturalEvents", columnName: "Cultural_Events", tableName: "Events" },
  { key: "seasonalActivities", columnName: "Seasonal_Activities", tableName: "Events" },
  { key: "yachtClubMembership", columnName: "Club_Membership", tableName: "Events" },
  { key: "socialEvents", columnName: "Social_Events", tableName: "Events" },
  { key: "regattasAndCompetitions", columnName: "Regattas", tableName: "Events" },
  { key: "workshopsAndClasses", columnName: "Workshops_Classes", tableName: "Events" },
  { key: "boatShows", columnName: "Boat_Shows", tableName: "Events" }
];

export const UNIQUE_TABLE = [
    "Marina_Port",
    "Berths",
    "Amenities",
    "Family",
    "Local_Area",
    "Berth_Features",
    "Events",
    "Operations",
    "Repairs",
    "Accessibility",
    "Connectivity",
    "Environment",
    "Safety_Procedures",
    "Legal",
    "Insurance",
    "Financial",
    "Pricing",
    "Berth_Payment",
    "Berth_Sales",
];

