export const varToColumn = {
    // Job Description
    marisailTransportID: "Transport_Item_ID",
    dataSource: "Data_Source",
    category: "Category",
    title: "Title",
    description: "Description",
    postedDate: "Posted_Date",
    deadlineDate: "Deadline_Date",
    timescale: "Timescale",
    preferredDate: "Preferred_Date",
    haulierToDepartureDistance: "Collection_Delivery_Distance",
    departureToDestinationDistance: "Departure_Destination",
    returnJourney: "Return_Journey",
    roundTripDistance: "Round_Trip_Distance",
    international: "International",
    ferryRequired: "Ferry_Required?",
    specialHandlingRequirements: "Special_Handling",
    departureLoadingEquipmentNeeded: "Loading_Equipment",
    destinationUnloadingEquipmentNeeded: "Unloading_Equipment",
    freightClass: "Freight_Class",
    overweightPermitNeeded: "Overweight_Permit",
    oversizePermitNeeded: "Oversize_Permit",
    numberQuotes: "Number_Quotes",
    map: "Map",
    jobDone: "Job_Done",
    jobDoneDate: "Job_Done_Date",

    // Vessel Details
    itemNumber: "Item_Number",
    totalNumberItems: "Total_Number_Items",
    photos: "Photos",
    previousInsuranceClaims: "Insurance_Claims",
    existingDamage: "Existing_Damage",
    damageDescription: "Damage_Description",
    vesselInsuranceType: "Vessel_Insurance_Type",
    vesselInsuranceNotes: "Vessel_Insurance_Notes",

    // Customer Contact Details
    customerType: "Customer_Type",
    customerID: "Customer_ID",
    customerName: "Customer_Name",
    customerCompanyName: "Customer_Company_Name",
    collectionNamedContact: "Collection_Contact",
    collectionMobile: "Collection_Mobile",
    deliveryNamedContact: "Delivery_Contact",
    collectionAddress: "Collection_Address",
    deliveryMobile: "Delivery_Mobile",
    deliveryAddress: "Delivery_Address",
    emergencyContactInformation: "Emergency_Contacts",
    preferredCommunicationMethod: "Preferred_Communication",

    // Transport Quotes
    quote: "Quote_Value",
    quoteDescription: "Quote_Description",
    quoteDate: "Quote_Date",
    declineDate: "Decline_Date",
    withdrawDate: "Withdraw_Date",
    quoteStatus: "Quote_Status",

    // Q&A
    questionDate: "Question_Date",
    answerDate: "Answer_Date",
    transportProviderQuestions: "Transport_Provider_Questions",
    customerAnswers: "Customer_Answers",

    // Feedback
    customerFeedbackNotes: "Customer_Feedback_Notes",
    customerFeedbackScore: "Customer_Feedback_Score",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    reviews: "Reviews",
    rating: "Rating",
    itemTitle: "Item_Title",
    leftBy: "Left_By",
    comments: "Comments",
    date: "Date",
    seeMyQuotes: "See_My_Quotes",

    // Haulier Details
    haulierID: "Haulier_ID",
    haulierAddress: "Haulier_Address",
    haulierName: "Haulier_Name",
    haulierNumberJobs: "Haulier_Number_Jobs",
    haulierTotalCustomerScore: "Haulier_Total_Customer_Score",
    registeredSince: "Registered_Since",
    numberVehicles: "Number_Vehicles",
    numberDrivers: "Number_Drivers",
    verified: "Verified",
    vehicleType: "Vehicle_Type",
    vehicleCapacity: "Vehicle_Capacity",

    // Haulier Communications
    customerServiceContactInformation: "Customer_Service",
    realTimeTracking: "Real_Time_Tracking",
    electronicProofOfDelivery: "Electronic_POD",
    automatedAlertsNotifications: "Automated_Alerts",
    trackingSystem: "Tracking_System",
    deliveryWindow: "Delivery_Window",
    deliveryConfirmation: "Delivery_Confirmation",

    // Haulier Safety & Compliance
    safetyCertifications: "Safety_Certifications",
    environmentalRegulationsCompliance: "Environmental_Regulations",
    hazardousMaterialsHandling: "Hazardous_Materials",
    safetyTrainingPrograms: "Safety_Training",
    accidentReportingProcedures: "Accident_Reporting",
    healthSafetyPolicies: "Health_Safety",
    safetyAudits: "Safety_Audits",
    riskAssessments: "Risk_Assessments",
    incidentManagement: "Incident_Management",
    complianceRecords: "Compliance_Records",
    permitsLicenses: "Permits",
    transportRegulationsCompliance: "Transport_Regulations",

    // Payment & Insurance
    paymentTerms: "Payment_Terms",
    serviceLevelAgreement: "SLA",
    acceptedPaymentMethods: "Payment_Methods",
    cancellationPolicy: "Cancellation_Policy",
    currency: "Currency",
    invoiceTime: "Invoice_Time",
    latePaymentFees: "Late_Fees",
    billingContactInformation: "Billing_Contact",
    disputeResolutionTerms: "Dispute_Resolution",
    liabilityCoverage: "Liability_Coverage",
    insurancePolicy: "Insurance_Policy",
    insuranceCoverage: "Insurance_Coverage",
    insuranceProvider: "Insurance_Provider",
    insuranceClaimProcess: "Claim_Process",


    // Payment Terms
    // paymentTerms: "Payment_Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred_Payment",
    invoiceReceiptProcedures: "Invoice_Receipt",

    // Calculate Price & Pay
    calculatePricePay: "Calculate",
    priceLabel: "Price_Label",
    priceDrop: "Price_Drop",
    // currency: "Currency",
    vat: "VAT",
}

export const varToTable = {
    jobDescription: "Job",
    vesselDetails: "Vessel_Details",
    customerContactDetails: "Contacts",
    transportQuotes: "Quotes",
    qAndA: "Questions",
    feedback: "Reviews",
    haulierDetails: "Haulier",
    haulierCommunications: "Haulier",
    haulierSafetyCompliance: "Compliance",
    paymentInsurance: "Transport_Payment",
    paymentTerms: "Transport_Payment",
    calculatePricePay: "Transportation_Sales",
}

export const uniqueTable = [
    "Job",
    "Vessel_Details",
    "Contacts",
    "Quotes",
    "Questions",
    "Reviews",
    "Haulier",
    "Compliance",
    "Transport_Payment",
    "Transportation_Sales",
]

