export const typeDef = {
    jobDescription: {
        marisailTransportId: { value: "", type: "radio", mandatory: false },
        category: { value: "", type: "radio", mandatory: true },
        title: { value: "", type: "radio", mandatory: true },
        description: { value: "", type: "radio", mandatory: true },
        postedDate: { value: "", type: "date", mandatory: false },
        deadlineDate: { value: "", type: "radio", mandatory: true },
        timescale: { value: "", type: "radio", mandatory: true },
        preferredDate: { value: "", type: "radio", mandatory: true },
        haulierToDepartureDistance: { value: "", type: "radio", mandatory: false },
        departureToDestinationDistance: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        returnJourney: { value: "", type: "radio", mandatory: false },
        roundTripDistance: { value: "", type: "radio", mandatory: false },
        international: { value: "", type: "radio", mandatory: true },
        ferryRequired: { value: "", type: "radio", mandatory: true },
        specialHandlingRequirements: { value: "", type: "radio", mandatory: true },
        departureLoadingEquipmentNeeded: {
            value: "",
            type: "radio",
            mandatory: true,
        },
        destinationUnloadingEquipmentNeeded: {
            value: "",
            type: "radio",
            mandatory: true,
        },
        freightClass: { value: "", type: "radio", mandatory: false },
        overweightPermitNeeded: { value: "", type: "radio", mandatory: true },
        oversizePermitNeeded: { value: "", type: "radio", mandatory: true },
        numberQuotes: { value: "", type: "radio", mandatory: false },
        map: { value: "", type: "radio", mandatory: false },
        jobDone: { value: "", type: "radio", mandatory: false },
        jobDoneDate: { value: "", type: "radio", mandatory: false },
    },
    vesselDetails: {
        itemNumber: { value: "", type: "radio", mandatory: true },
        totalNumberItems: { value: "", type: "radio", mandatory: true },
        photos: { value: "", type: "radio", mandatory: false },
        previousInsuranceClaims: { value: "", type: "radio", mandatory: true },
        existingDamage: { value: "", type: "radio", mandatory: true },
        damageDescription: { value: "", type: "radio", mandatory: true },
        vesselInsuranceType: { value: "", type: "radio", mandatory: true },
        vesselInsuranceNotes: { value: "", type: "radio", mandatory: true },
        boatDetails: { value: "", type: "radio", mandatory: false },
    },
    customerContactDetails: {
        customerType: { value: "", type: "radio", mandatory: true },
        customerId: { value: "", type: "radio", mandatory: false },
        customerName: { value: "", type: "radio", mandatory: false },
        customerCompanyName: { value: "", type: "radio", mandatory: false },
        collectionDepartureNamedContact: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        collectionDepartureMobile: { value: "", type: "radio", mandatory: false },
        deliveryDestinationNamedContact: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        collectionDepartureAddress: { value: "", type: "radio", mandatory: false },
        deliveryDestinationMobile: { value: "", type: "radio", mandatory: false },
        deliveryDestinationAddress: { value: "", type: "radio", mandatory: false },
        emergencyContactInformation: { value: "", type: "radio", mandatory: false },
        preferredCommunicationMethod: { value: "", type: "radio", mandatory: false },
    },
    transportQuotes: {
        quote: { value: "", type: "radio", mandatory: true },
        quoteDescription: { value: "", type: "radio", mandatory: false },
        quoteDate: { value: "", type: "radio", mandatory: false },
        declineDate: { value: "", type: "radio", mandatory: false },
        withdrawDate: { value: "", type: "radio", mandatory: false },
        quoteStatus: { value: "", type: "radio", mandatory: false },
        declineQuote: { value: "", type: "radio", mandatory: false },
        withdrawQuote: { value: "", type: "radio", mandatory: false },
    },
    qAndA: {
        questionDate: { value: "", type: "radio", mandatory: false },
        answerDate: { value: "", type: "radio", mandatory: true },
        transportProviderQuestions: { value: "", type: "radio", mandatory: false },
        customerAnswers: { value: "", type: "radio", mandatory: false },
        writeQuestion: { value: "", type: "radio", mandatory: false },
        answerQuestion: { value: "", type: "radio", mandatory: false },
        customerConfirmsCompletion: { value: "", type: "radio", mandatory: false },
        addItem: { value: "", type: "radio", mandatory: false },
    },
    feedback: {
        customerFeedbackNotes: { value: "", type: "radio", mandatory: true },
        customerFeedbackScore: { value: "", type: "radio", mandatory: false },
        positive: { value: "", type: "radio", mandatory: false },
        neutral: { value: "", type: "radio", mandatory: false },
        negative: { value: "", type: "radio", mandatory: false },
        reviews: { value: "", type: "radio", mandatory: false },
        rating: { value: "", type: "radio", mandatory: false },
        itemTitle: { value: "", type: "radio", mandatory: false },
        leftBy: { value: "", type: "radio", mandatory: false },
        comments: { value: "", type: "radio", mandatory: false },
        date: { value: "", type: "radio", mandatory: false },
        customerGivesFeedbackNotes: { value: "", type: "radio", mandatory: false },
        customerGivesFeedbackScore: { value: "", type: "radio", mandatory: false },
        seeMyQuotes: { value: "", type: "radio", mandatory: false },
    },
    haulierDates: {
        haulierId: { value: "", type: "radio", mandatory: false },
        haulierAddress: { value: "", type: "radio", mandatory: false },
        haulierName: { value: "", type: "radio", mandatory: false },
        haulierNumberJobs: { value: "", type: "radio", mandatory: false },
        haulierTotalCustomerScore: { value: "", type: "radio", mandatory: false },
        registeredSince: { value: "", type: "radio", mandatory: true },
        numberVehicles: { value: "", type: "radio", mandatory: true },
        numberDrivers: { value: "", type: "radio", mandatory: true },
        verified: { value: "", type: "radio", mandatory: true },
        vehicleType: { value: "", type: "radio", mandatory: false },
        vehicleCapacity: { value: "", type: "radio", mandatory: false },
    },
    haulierCommunications: {
        customerServiceContactInformation: {
            value: "",
            type: "radio",
            mandatory: false,
        },
        realTimeTracking: { value: "", type: "radio", mandatory: true },
        electronicProofOfDelivery: { value: "", type: "radio", mandatory: true },
        automatedAlertsAndNotifications: { value: "", type: "radio", mandatory: true },
        trackingSystem: { value: "", type: "radio", mandatory: false },
        deliveryWindow: { value: "", type: "radio", mandatory: false },
        deliveryConfirmation: { value: "", type: "radio", mandatory: false },
    },
    haulierSafetyAndCompliance: {
        safetyCertifications: { value: "", type: "radio", mandatory: true },
        environmentalRegulationsCompliance: {
            value: "",
            type: "radio",
            mandatory: true,
        },
        hazardousMaterialsHandling: { value: "", type: "radio", mandatory: true },
        safetyTrainingPrograms: { value: "", type: "radio", mandatory: true },
        accidentReportingProcedures: { value: "", type: "radio", mandatory: true },
        healthAndSafetyPolicies: { value: "", type: "radio", mandatory: true },
        safetyAudits: { value: "", type: "radio", mandatory: true },
        riskAssessments: { value: "", type: "radio", mandatory: true },
        incidentManagement: { value: "", type: "radio", mandatory: true },
        complianceRecords: { value: "", type: "radio", mandatory: true },
        permitsAndLicenses: { value: "", type: "radio", mandatory: true },
        transportRegulationsCompliance: { value: "", type: "radio", mandatory: true },
    },
    paymentAndInsurance: {
        serviceLevelAgreement: { value: "", type: "radio", mandatory: false },
        acceptedPaymentMethods: { value: "", type: "radio", mandatory: true },
        cancellationPolicy: { value: "", type: "radio", mandatory: true },
        currency: { value: "", type: "radio", mandatory: true },
        invoiceTime: { value: "", type: "radio", mandatory: true },
        latePaymentFees: { value: "", type: "radio", mandatory: true },
        billingContactInformation: { value: "", type: "radio", mandatory: false },
        disputeResolutionTerms: { value: "", type: "radio", mandatory: true },
        liabilityCoverage: { value: "", type: "radio", mandatory: true },
        insurancePolicy: { value: "", type: "radio", mandatory: true },
        insuranceCoverage: { value: "", type: "radio", mandatory: true },
        insuranceProvider: { value: "", type: "radio", mandatory: true },
        insuranceClaimProcess: { value: "", type: "radio", mandatory: true },
    },
    paymentTerms: {
        paymentTerms: { value: "", type: "radio", mandatory: true },
        priceLabel: { value: "", type: "radio", mandatory: false },
        priceDrop: { value: "", type: "radio", mandatory: false },
        vat: { value: "", type: "radio", mandatory: false },
        invoiceAndReceiptProcedures: { value: "", type: "radio", mandatory: true },
        preferredPaymentMethods: { value: "", type: "radio", mandatory: true },
        calculatePriceAndPay: { value: "", type: "radio", mandatory: false },
    }
};

export const keyToExpectedValueMap = {
    ferryRequired: "Ferry Required?",
    departureLoadingEquipmentNeeded: "Departure Loading Equipment Needed?",
    overweightPermitNeeded: "Overweight Permit Needed?",
    oversizePermitNeeded: "Oversize Permit Needed?",
    existingDamage: "Existing Damage?",
    collectionDepartureNamedContact: "Collection (Departure) Named Contact",
    collectionDepartureMobile: "Collection (Departure) Mobile",
    deliveryDestinationNamedContact: "Delivery (Destination) Named Contact",
    collectionDepartureAddress: "Collection (Departure) Address",
    deliveryDestinationMobile: "Delivery (Destination) Mobile",
    deliveryDestinationAddress: "Delivery (Destination) Address",
    itemTitle: "Item - Title",
    realTimeTracking: "Real-Time Tracking",
    serviceLevelAgreement: "Service Level Agreement (SLA)",
    vat: "VAT"
};
