export const typeDef = {
    jobDescription: {
        marisailTransportId: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        category: { value: "", radioOptions: null, type: "radio", mandatory: true },
        title: { value: "", radioOptions: null, type: "radio", mandatory: true },
        description: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        postedDate: {
            value: new Date(),
            radioOptions: null,
            type: "date",
            mandatory: false,
        },
        deadlineDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        timescale: {
            value: new Date(),
            radioOptions: null,
            type: "date",
            mandatory: true,
        },
        preferredDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        haulierToDepartureDistance: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        departureToDestinationDistance: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        returnJourney: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        roundTripDistance: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        international: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        ferryRequired: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        specialHandlingRequirements: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        departureLoadingEquipmentNeeded: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        destinationUnloadingEquipmentNeeded: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        freightClass: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        overweightPermitNeeded: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        oversizePermitNeeded: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        numberQuotes: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        map: { value: "", radioOptions: null, type: "radio", mandatory: false },
        jobDone: { value: "", radioOptions: null, type: "radio", mandatory: false },
        jobDoneDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
    vesselDetails: {
        itemNumber: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        totalNumberItems: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        photos: { value: "", radioOptions: null, type: "radio", mandatory: false },
        previousInsuranceClaims: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        existingDamage: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        damageDescription: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        vesselInsuranceType: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        vesselInsuranceNotes: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        boatDetails: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
    customerContactDetails: {
        customerType: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        customerId: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        customerName: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        customerCompanyName: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        collectionDepartureNamedContact: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        collectionDepartureMobile: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        deliveryDestinationNamedContact: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        collectionDepartureAddress: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        deliveryDestinationMobile: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        deliveryDestinationAddress: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        emergencyContactInformation: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        preferredCommunicationMethod: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
    transportQuotes: {
        quote: { value: "", radioOptions: null, type: "radio", mandatory: true },
        quoteDescription: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        quoteDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        declineDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        withdrawDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        quoteStatus: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        declineQuote: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        withdrawQuote: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
    qAndA: {
        questionDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        answerDate: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        transportProviderQuestions: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        customerAnswers: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        writeQuestion: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        answerQuestion: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        customerConfirmsCompletion: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        addItem: { value: "", radioOptions: null, type: "radio", mandatory: false },
    },
    feedback: {
        customerFeedbackNotes: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        customerFeedbackScore: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        positive: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        neutral: { value: "", radioOptions: null, type: "radio", mandatory: false },
        negative: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        reviews: { value: "", radioOptions: null, type: "radio", mandatory: false },
        rating: { value: "", radioOptions: null, type: "radio", mandatory: false },
        itemTitle: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        leftBy: { value: "", radioOptions: null, type: "radio", mandatory: false },
        comments: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        date: { value: "", radioOptions: null, type: "radio", mandatory: false },
        customerGivesFeedbackNotes: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        customerGivesFeedbackScore: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        seeMyQuotes: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
    haulierDates: {
        haulierId: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        haulierAddress: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        haulierName: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        haulierNumberJobs: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        haulierTotalCustomerScore: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        registeredSince: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        numberVehicles: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        numberDrivers: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        verified: { value: "", radioOptions: null, type: "radio", mandatory: true },
        vehicleType: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        vehicleCapacity: {
            value: "",
            radioOptions: [
                { label: "Kg", value: "Kg", id: 1 },
                { label: "Ton", value: "Ton", id: 2 },
            ],
            type: "dual",
            mandatory: false,
        },
    },
    haulierCommunications: {
        customerServiceContactInformation: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        realTimeTracking: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        electronicProofOfDelivery: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        automatedAlertsAndNotifications: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        trackingSystem: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        deliveryWindow: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        deliveryConfirmation: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
    haulierSafetyAndCompliance: {
        safetyCertifications: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        environmentalRegulationsCompliance: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        hazardousMaterialsHandling: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        safetyTrainingPrograms: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        accidentReportingProcedures: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        healthAndSafetyPolicies: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        safetyAudits: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        riskAssessments: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        incidentManagement: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        complianceRecords: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        permitsAndLicenses: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        transportRegulationsCompliance: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
    },
    paymentAndInsurance: {
        serviceLevelAgreement: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        acceptedPaymentMethods: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        cancellationPolicy: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        currency: { value: "", radioOptions: null, type: "radio", mandatory: true },
        invoiceTime: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        latePaymentFees: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        billingContactInformation: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        disputeResolutionTerms: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        liabilityCoverage: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        insurancePolicy: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        insuranceCoverage: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        insuranceProvider: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        insuranceClaimProcess: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
    },
    paymentTerms: {
        paymentTerms: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        priceLabel: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        priceDrop: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
        vat: { value: "", radioOptions: null, type: "radio", mandatory: false },
        invoiceAndReceiptProcedures: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        preferredPaymentMethods: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: true,
        },
        calculatePriceAndPay: {
            value: "",
            radioOptions: null,
            type: "radio",
            mandatory: false,
        },
    },
};

export const keyToExpectedValueMap = {
    ferryRequired: "Ferry Required?",
    departureLoadingEquipmentNeeded: "Departure Loading Equipment Needed?",
    overweightPermitNeeded: "Overweight Permit Needed?",
    oversizePermitNeeded: "Oversize Permit Needed?",
    existingDamage: "Existing Damage?",
    collectionDepartureNamedContact: "Collection (Departure) Named Contact",
    collectionDepartureMobile: "Collection (Departure) Mobile",
    deliveryDestinationNamedContact: "Delivery (Destination) Named Contact",
    collectionDepartureAddress: "Collection (Departure) Address",
    deliveryDestinationMobile: "Delivery (Destination) Mobile",
    deliveryDestinationAddress: "Delivery (Destination) Address",
    itemTitle: "Item - Title",
    realTimeTracking: "Real-Time Tracking",
    serviceLevelAgreement: "Service Level Agreement (SLA)",
    vat: "VAT",
};
