export const varToScreen = {
    // Job Description
    jobDescription: "Job Description",
    marisailTransportID: "Marisail Transport ID",
    dataSource: "Data Source",
    category: "Category",
    title: "Title",
    description: "Description",
    postedDate: "Posted Date",
    deadlineDate: "Deadline Date",
    timescale: "Timescale",
    preferredDate: "Preferred Date",
    haulierToDepartureDistance: "Haulier To Departure Distance",
    departureToDestinationDistance: "Departure To Destination Distance",
    returnJourney: "Return Journey",
    roundTripDistance: "Round Trip Distance",
    international: "International",
    ferryRequired: "Ferry Required?",
    specialHandlingRequirements: "Special Handling Requirements",
    departureLoadingEquipmentNeeded: "Departure Loading Equipment Needed?",
    destinationUnloadingEquipmentNeeded: "Destination Unloading Equipment Needed",
    freightClass: "Freight Class",
    overweightPermitNeeded: "Overweight Permit Needed?",
    oversizePermitNeeded: "Oversize Permit Needed?",
    numberQuotes: "Number Quotes",
    map: "Map",
    jobDone: "Job Done",
    jobDoneDate: "Job Done Date",
    
    
    // Vessel Details
    vesselDetails: "Vessel Details",
    itemNumber: "Item Number",
    totalNumberItems: "Total Number Items",
    photos: "Photos",
    previousInsuranceClaims: "Previous Insurance Claims",
    existingDamage: "Existing Damage?",
    damageDescription: "Damage Description",
    vesselInsuranceType: "Vessel Insurance Type",
    vesselInsuranceNotes: "Vessel Insurance Notes",
    boatDetails: "Boat Details",

    // Customer Contact Details
    customerContactDetails: "Customer Contact Details",
    customerType: "Customer Type",
    customerID: "Customer ID",
    customerName: "Customer Name",
    customerCompanyName: "Customer Company Name",
    collectionNamedContact: "Collection (Departure) Named Contact",
    collectionMobile: "Collection (Departure) Mobile",
    deliveryNamedContact: "Delivery (Destination) Named Contact",
    collectionAddress: "Collection (Departure) Address",
    deliveryMobile: "Delivery (Destination) Mobile",
    deliveryAddress: "Delivery (Destination) Address",
    emergencyContactInformation: "Emergency Contact Information",
    preferredCommunicationMethod: "Preferred Communication Method",

    // Transport Quotes
    transportQuotes: "Transport Quotes",
    quote: "Quote",
    quoteDescription: "Quote Description",
    quoteDate: "Quote Date",
    declineDate: "Decline Date",
    withdrawDate: "Withdraw Date",
    quoteStatus: "Quote Status",
    declineQuote: "Decline Quote",
    withdrawQuote: "Withdraw Quote",

    // Q&A
    qAndA: "Q&A",
    questionDate: "Question Date",
    answerDate: "Answer Date",
    transportProviderQuestions: "Transport Provider Questions",
    customerAnswers: "Customer Answers",
    writeQuestion: "Write Question",
    answerQuestion: "Answer Question",
    customerConfirmsCompletion: "Customer Confirms Completion",
    addItem: "Add Item",

    // Feedback
    feedback: "Feedback",
    customerFeedbackNotes: "Customer Feedback Notes",
    customerFeedbackScore: "Customer Feedback Score",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    reviews: "Reviews",
    rating: "Rating",
    itemTitle: "Item - Title",
    leftBy: "Left By",
    comments: "Comments",
    date: "Date",
    customerGivesFeedbackNotes: "Customer Gives Feedback Notes",
    customerGivesFeedbackScore: "Customer Gives Feedback Score",
    seeMyQuotes: "See My Quotes",

    // Haulier Details
    haulierDetails: "Haulier Details",
    haulierID: "Haulier ID",
    haulierAddress: "Haulier Address",
    haulierName: "Haulier Name",
    haulierNumberJobs: "Haulier Number Jobs",
    haulierTotalCustomerScore: "Haulier Total Customer Score",
    registeredSince: "Registered Since",
    numberVehicles: "Number Vehicles",
    numberDrivers: "Number Drivers",
    verified: "Verified",
    vehicleType: "Vehicle Type",
    vehicleCapacity: "Vehicle Capacity",
    
    // Haulier Communications
    haulierCommunications: "Haulier Communications",
    customerServiceContactInformation: "Customer Service Contact Information",
    realTimeTracking: "Real-Time Tracking",
    electronicProofOfDelivery: "Electronic Proof of Delivery",
    automatedAlertsNotifications: "Automated Alerts & Notifications",
    trackingSystem: "Tracking System",
    deliveryWindow: "Delivery Window",
    deliveryConfirmation: "Delivery Confirmation",

    // Haulier Safety & Compliance
    haulierSafetyCompliance: "Haulier Safety & Compliance",
    safetyCertifications: "Safety Certifications",
    environmentalRegulationsCompliance: "Environmental Regulations Compliance",
    hazardousMaterialsHandling: "Hazardous Materials Handling",
    safetyTrainingPrograms: "Safety Training Programs",
    accidentReportingProcedures: "Accident Reporting Procedures",
    healthSafetyPolicies: "Health & Safety Policies",
    safetyAudits: "Safety Audits",
    riskAssessments: "Risk Assessments",    
    incidentManagement: "Incident Management",
    complianceRecords: "Compliance Records",
    permitsLicenses: "Permits & Licenses",
    transportRegulationsCompliance: "Transport Regulations Compliance",

    // Payment & Insurance
    paymentInsurance: "Payment & Insurance",
    paymentTerms: "Payment Terms",
    serviceLevelAgreement: "Service Level Agreement (SLA)",
    acceptedPaymentMethods: "Accepted Payment Methods",
    cancellationPolicy: "Cancellation Policy",
    currency: "Currency",   
    invoiceTime: "Invoice Time",
    latePaymentFees: "Late Payment Fees",
    billingContactInformation: "Billing Contact Information",
    disputeResolutionTerms: "Dispute Resolution Terms",
    liabilityCoverage: "Liability Coverage",
    insurancePolicy: "Insurance Policy",
    insuranceCoverage: "Insurance Coverage",
    insuranceProvider: "Insurance Provider",
    insuranceClaimProcess: "Insurance Claim Process",

    // Payment Terms
    // paymentTerms: "Payment Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred Payment Methods",
    invoiceReceiptProcedures: "Invoice & Receipt Procedures",
    
    // Calculate Price & Pay
    calculatePricePay: "Calculate Price & Pay",
    priceLabel: "Price Label",
    priceDrop: "Price Drop",
    // currency: "Currency",
    vat: "VAT",
    totalPrice: "Total Price",

    // Contact Details
    contactDetails: "Contact Details",
    uploadPhotos: "Upload Photos",
    uploadVideos: "Upload Videos",  
}

export const varToDb = {
    // Job Description
    marisailTransportID: "Transport_Item_ID",
    dataSource: "Data_Source",
    category: "Category",
    title: "Title",
    description: "Description",
    postedDate: "Posted_Date",
    deadlineDate: "Deadline_Date",
    timescale: "Timescale",
    preferredDate: "Preferred_Date",
    haulierToDepartureDistance: "Collection_Delivery_Distance",
    departureToDestinationDistance: "Departure_Destination",
    returnJourney: "Return_Journey",
    roundTripDistance: "Round_Trip_Distance",
    international: "International",
    ferryRequired: "Ferry_Required?",
    specialHandlingRequirements: "Special_Handling",
    departureLoadingEquipmentNeeded: "Loading_Equipment",
    destinationUnloadingEquipmentNeeded: "Unloading_Equipment",
    freightClass: "Freight_Class",
    overweightPermitNeeded: "Overweight_Permit",
    oversizePermitNeeded: "Oversize_Permit",
    numberQuotes: "Number_Quotes",
    map: "Map",
    jobDone: "Job_Done",
    jobDoneDate: "Job_Done_Date",

    // Vessel Details
    itemNumber: "Item_Number",
    totalNumberItems: "Total_Number_Items",
    photos: "Photos",
    previousInsuranceClaims: "Insurance_Claims",
    existingDamage: "Existing_Damage",
    damageDescription: "Damage_Description",
    vesselInsuranceType: "Vessel_Insurance_Type",
    vesselInsuranceNotes: "Vessel_Insurance_Notes",

    // Customer Contact Details
    customerType: "Customer_Type",
    customerID: "Customer_ID",
    customerName: "Customer_Name",
    customerCompanyName: "Customer_Company_Name",
    collectionNamedContact: "Collection_Contact",
    collectionMobile: "Collection_Mobile",
    deliveryNamedContact: "Delivery_Contact",
    collectionAddress: "Collection_Address",
    deliveryMobile: "Delivery_Mobile",
    deliveryAddress: "Delivery_Address",
    emergencyContactInformation: "Emergency_Contacts",
    preferredCommunicationMethod: "Preferred_Communication",

    // Transport Quotes
    quote: "Quote_Value",
    quoteDescription: "Quote_Description",
    quoteDate: "Quote_Date",
    declineDate: "Decline_Date",
    withdrawDate: "Withdraw_Date",
    quoteStatus: "Quote_Status",

    // Q&A
    questionDate: "Question_Date",
    answerDate: "Answer_Date",
    transportProviderQuestions: "Transport_Provider_Questions",
    customerAnswers: "Customer_Answers",

    // Feedback
    customerFeedbackNotes: "Customer_Feedback_Notes",
    customerFeedbackScore: "Customer_Feedback_Score",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    reviews: "Reviews",
    rating: "Rating",
    itemTitle: "Item_Title",
    leftBy: "Left_By",
    comments: "Comments",
    date: "Date",
    seeMyQuotes: "See_My_Quotes",

    // Haulier Details
    haulierID: "Haulier_ID",
    haulierAddress: "Haulier_Address",
    haulierName: "Haulier_Name",
    haulierNumberJobs: "Haulier_Number_Jobs",
    haulierTotalCustomerScore: "Haulier_Total_Customer_Score",
    registeredSince: "Registered_Since",
    numberVehicles: "Number_Vehicles",
    numberDrivers: "Number_Drivers",
    verified: "Verified",
    vehicleType: "Vehicle_Type",
    vehicleCapacity: "Vehicle_Capacity",

    // Haulier Communications
    customerServiceContactInformation: "Customer_Service",
    realTimeTracking: "Real_Time_Tracking",
    electronicProofOfDelivery: "Electronic_POD",
    automatedAlertsNotifications: "Automated_Alerts",
    trackingSystem: "Tracking_System",
    deliveryWindow: "Delivery_Window",
    deliveryConfirmation: "Delivery_Confirmation",

    // Haulier Safety & Compliance
    safetyCertifications: "Safety_Certifications",
    environmentalRegulationsCompliance: "Environmental_Regulations",
    hazardousMaterialsHandling: "Hazardous_Materials",
    safetyTrainingPrograms: "Safety_Training",
    accidentReportingProcedures: "Accident_Reporting",
    healthSafetyPolicies: "Health_Safety",
    safetyAudits: "Safety_Audits",
    riskAssessments: "Risk_Assessments",
    incidentManagement: "Incident_Management",
    complianceRecords: "Compliance_Records",
    permitsLicenses: "Permits",
    transportRegulationsCompliance: "Transport_Regulations",

    // Payment & Insurance
    paymentTerms: "Payment_Terms",
    serviceLevelAgreement: "SLA",
    acceptedPaymentMethods: "Payment_Methods",
    cancellationPolicy: "Cancellation_Policy",
    currency: "Currency",
    invoiceTime: "Invoice_Time",
    latePaymentFees: "Late_Fees",
    billingContactInformation: "Billing_Contact",
    disputeResolutionTerms: "Dispute_Resolution",
    liabilityCoverage: "Liability_Coverage",
    insurancePolicy: "Insurance_Policy",
    insuranceCoverage: "Insurance_Coverage",
    insuranceProvider: "Insurance_Provider",
    insuranceClaimProcess: "Claim_Process",


    // Payment Terms
    // paymentTerms: "Payment_Terms",
    // currency: "Currency",
    preferredPaymentMethods: "Preferred_Payment",
    invoiceReceiptProcedures: "Invoice_Receipt",

    // Calculate Price & Pay
    calculatePricePay: "Calculate",
    priceLabel: "Price_Label",
    priceDrop: "Price_Drop",
    // currency: "Currency",
    vat: "VAT",
}